"""Business-rule enumerations."""

from __future__ import annotations

from enum import StrEnum


class RuleType(StrEnum):
    TONNAGE_MAX = "TONNAGE_MAX"
    GEOFENCE_RADIUS = "GEOFENCE_RADIUS"
    QTY_TOLERANCE = "QTY_TOLERANCE"
    PRICE_TOLERANCE = "PRICE_TOLERANCE"
    APPROVAL_LIMIT = "APPROVAL_LIMIT"
    REORDER_LEVEL = "REORDER_LEVEL"
    LATE_SUBMISSION = "LATE_SUBMISSION"
    DUPLICATE_WINDOW = "DUPLICATE_WINDOW"
    DAILY_DELIVERY_CAP = "DAILY_DELIVERY_CAP"
    CLOCK_SKEW_MAX = "CLOCK_SKEW_MAX"
    PURCHASE_LIMIT = "PURCHASE_LIMIT"
