"""business rules

Revision ID: 759939546f42
Revises: 0b818b783b15
Created: 2026-09-26 03:34:27.562714+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "759939546f42"
down_revision: str | None = "0b818b783b15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("rule_type", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "rule_type IN ('TONNAGE_MAX', 'GEOFENCE_RADIUS', 'QTY_TOLERANCE', 'PRICE_TOLERANCE', 'APPROVAL_LIMIT', 'REORDER_LEVEL', 'LATE_SUBMISSION', 'DUPLICATE_WINDOW', 'DAILY_DELIVERY_CAP', 'CLOCK_SKEW_MAX', 'PURCHASE_LIMIT')",
            name=op.f("ck_business_rules_rule_type_valid"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_business_rules_effective_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_business_rules_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_rules")),
    )
    op.create_index(
        op.f("ix_business_rules_company_id"), "business_rules", ["company_id"], unique=False
    )
    op.create_index(
        "ix_business_rules_type",
        "business_rules",
        ["company_id", "rule_type", "is_active"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_business_rules_type", table_name="business_rules")
    op.drop_index(op.f("ix_business_rules_company_id"), table_name="business_rules")
    op.drop_table("business_rules")
    # ### end Alembic commands ###
