"""approval engine and purchase requests

Revision ID: a1e7e9334421
Revises: abdbd88f57ce
Created: 2026-09-24 15:03:36.928342+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a1e7e9334421"
down_revision: str | None = "abdbd88f57ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_workflows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("doc_type", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_note", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "scope_type IN ('COMPANY', 'PROJECT')",
            name=op.f("ck_approval_workflows_scope_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_approval_workflows_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_workflows")),
        sa.UniqueConstraint(
            "company_id",
            "doc_type",
            "scope_type",
            "scope_id",
            "version",
            name="uq_approval_workflows_version",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_approval_workflows_company_id"), "approval_workflows", ["company_id"], unique=False
    )
    op.create_index(
        "uq_approval_workflows_one_active",
        "approval_workflows",
        [
            "company_id",
            "doc_type",
            "scope_type",
            sa.literal_column("coalesce(scope_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
        ],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("doc_type", sa.String(length=40), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("doc_number", sa.String(length=40), nullable=True),
        sa.Column("doc_summary", sa.String(length=300), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("link_path", sa.String(length=200), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_version", sa.Integer(), nullable=False),
        sa.Column("workflow_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("document_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_step_no", sa.Integer(), nullable=True),
        sa.Column("initiated_by_id", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome_reason", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED', 'RECALLED', 'CHANGES_REQUESTED')",
            name=op.f("ck_approval_requests_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_approval_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["approval_workflows.id"],
            name=op.f("fk_approval_requests_workflow_id_approval_workflows"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_requests")),
    )
    op.create_index(
        op.f("ix_approval_requests_company_id"), "approval_requests", ["company_id"], unique=False
    )
    op.create_index(
        "ix_approval_requests_document", "approval_requests", ["doc_type", "doc_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_requests_project_id"), "approval_requests", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_requests_site_id"), "approval_requests", ["site_id"], unique=False
    )
    op.create_index(
        "uq_approval_requests_one_open",
        "approval_requests",
        ["doc_type", "doc_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "approval_request_steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("approver_type", sa.String(length=20), nullable=False),
        sa.Column("approver_ref", sa.String(length=120), nullable=True),
        sa.Column("quorum_type", sa.String(length=10), nullable=False),
        sa.Column("quorum_required", sa.Integer(), nullable=False),
        sa.Column("approvals_count", sa.Integer(), nullable=False),
        sa.Column("sla_hours", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('WAITING', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')",
            name=op.f("ck_approval_request_steps_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["approval_requests.id"],
            name=op.f("fk_approval_request_steps_request_id_approval_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_request_steps")),
        sa.UniqueConstraint("request_id", "step_no", name="uq_approval_request_steps_no"),
    )
    op.create_index(
        "ix_approval_request_steps_pending_due",
        "approval_request_steps",
        ["status", "due_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index(
        op.f("ix_approval_request_steps_request_id"),
        "approval_request_steps",
        ["request_id"],
        unique=False,
    )
    op.create_table(
        "approval_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("request_step_id", sa.UUID(), nullable=True),
        sa.Column("step_no", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_name", sa.String(length=160), nullable=True),
        sa.Column("comments", sa.String(length=2000), nullable=True),
        sa.Column("acted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acted_ip", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "action IN ('SUBMIT', 'APPROVE', 'REJECT', 'REQUEST_CHANGES', 'RECALL', 'AUTO_RECALL', 'COMMENT', 'ESCALATE', 'AUTO_APPROVE')",
            name=op.f("ck_approval_actions_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["approval_requests.id"],
            name=op.f("fk_approval_actions_request_id_approval_requests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_step_id"],
            ["approval_request_steps.id"],
            name=op.f("fk_approval_actions_request_step_id_approval_request_steps"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_actions")),
    )
    op.create_index(
        op.f("ix_approval_actions_request_id"), "approval_actions", ["request_id"], unique=False
    )
    # docs/02 §12: the approval trail is append-only, enforced by the same
    # trigger as the audit log (function created in revision 2c50c3af7621).
    op.execute(
        """
        CREATE TRIGGER approval_actions_append_only
        BEFORE UPDATE OR DELETE ON approval_actions
        FOR EACH ROW EXECUTE FUNCTION krb_forbid_update_delete();
        """
    )
    op.create_table(
        "approval_step_approvers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_step_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "source IN ('RULE', 'ESCALATION')", name=op.f("ck_approval_step_approvers_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["request_step_id"],
            ["approval_request_steps.id"],
            name=op.f("fk_approval_step_approvers_request_step_id_approval_request_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_step_approvers")),
        sa.UniqueConstraint("request_step_id", "user_id", name="uq_approval_step_approvers_user"),
    )
    op.create_index(
        op.f("ix_approval_step_approvers_user_id"),
        "approval_step_approvers",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "purchase_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("pr_number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("cost_center_id", sa.UUID(), nullable=True),
        sa.Column("phase_id", sa.UUID(), nullable=True),
        sa.Column("required_date", sa.Date(), nullable=True),
        sa.Column("justification", sa.String(length=2000), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("estimated_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column("approval_request_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "priority IN ('NORMAL', 'URGENT')", name=op.f("ck_purchase_requests_priority_valid")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'CANCELLED', 'PARTIALLY_SOURCED', 'SOURCED')",
            name=op.f("ck_purchase_requests_status_valid"),
        ),
        sa.CheckConstraint(
            "estimated_amount >= 0", name=op.f("ck_purchase_requests_estimated_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_purchase_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cost_center_id"],
            ["cost_centers.id"],
            name=op.f("fk_purchase_requests_cost_center_id_cost_centers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_purchase_requests_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["project_phases.id"],
            name=op.f("fk_purchase_requests_phase_id_project_phases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_purchase_requests_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_purchase_requests_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_requests")),
        sa.UniqueConstraint("company_id", "pr_number", name="uq_purchase_requests_number"),
    )
    op.create_index(
        op.f("ix_purchase_requests_company_id"), "purchase_requests", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_requests_project_id"), "purchase_requests", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_requests_site_id"), "purchase_requests", ["site_id"], unique=False
    )
    op.create_index(
        "ix_purchase_requests_status", "purchase_requests", ["company_id", "status"], unique=False
    )
    op.create_table(
        "purchase_request_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("estimated_rate", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("estimated_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("required_date", sa.Date(), nullable=True),
        sa.Column("sourced_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "estimated_amount >= 0",
            name=op.f("ck_purchase_request_items_estimated_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "estimated_rate IS NULL OR estimated_rate >= 0",
            name=op.f("ck_purchase_request_items_estimated_rate_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_purchase_request_items_quantity_positive")
        ),
        sa.CheckConstraint(
            "sourced_quantity >= 0",
            name=op.f("ck_purchase_request_items_sourced_quantity_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_purchase_request_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["purchase_requests.id"],
            name=op.f("fk_purchase_request_items_request_id_purchase_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_purchase_request_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_request_items")),
        sa.UniqueConstraint("request_id", "line_no", name="uq_purchase_request_items_line"),
    )
    op.create_index(
        op.f("ix_purchase_request_items_material_id"),
        "purchase_request_items",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_request_items_request_id"),
        "purchase_request_items",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_request_items_request_id"), table_name="purchase_request_items")
    op.drop_index(
        op.f("ix_purchase_request_items_material_id"), table_name="purchase_request_items"
    )
    op.drop_table("purchase_request_items")
    op.drop_index("ix_purchase_requests_status", table_name="purchase_requests")
    op.drop_index(op.f("ix_purchase_requests_site_id"), table_name="purchase_requests")
    op.drop_index(op.f("ix_purchase_requests_project_id"), table_name="purchase_requests")
    op.drop_index(op.f("ix_purchase_requests_company_id"), table_name="purchase_requests")
    op.drop_table("purchase_requests")
    op.drop_index(op.f("ix_approval_step_approvers_user_id"), table_name="approval_step_approvers")
    op.drop_table("approval_step_approvers")
    op.execute("DROP TRIGGER IF EXISTS approval_actions_append_only ON approval_actions")
    op.drop_index(op.f("ix_approval_actions_request_id"), table_name="approval_actions")
    op.drop_table("approval_actions")
    op.drop_index(op.f("ix_approval_request_steps_request_id"), table_name="approval_request_steps")
    op.drop_index(
        "ix_approval_request_steps_pending_due",
        table_name="approval_request_steps",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("approval_request_steps")
    op.drop_index(
        "uq_approval_requests_one_open",
        table_name="approval_requests",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index(op.f("ix_approval_requests_site_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_project_id"), table_name="approval_requests")
    op.drop_index("ix_approval_requests_document", table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_company_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(
        "uq_approval_workflows_one_active",
        table_name="approval_workflows",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_approval_workflows_company_id"), table_name="approval_workflows")
    op.drop_table("approval_workflows")
    # ### end Alembic commands ###
