"""journal entry links on stock issues and adjustments

Revision ID: aa2278042938
Revises: a9d6e0a30e0d
Created: 2026-09-28 13:34:12.268367+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "aa2278042938"
down_revision: str | None = "a9d6e0a30e0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_adjustments", sa.Column("journal_entry_id", sa.UUID(), nullable=True))
    op.add_column("stock_issues", sa.Column("journal_entry_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_issues", "journal_entry_id")
    op.drop_column("stock_adjustments", "journal_entry_id")
    # ### end Alembic commands ###
