"""posting rules and budgets

Revision ID: a9d6e0a30e0d
Revises: 0c54c70e130b
Created: 2026-09-27 12:48:07.449980+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a9d6e0a30e0d"
down_revision: str | None = "0c54c70e130b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posting_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("event", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=True),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("debit_account_id", sa.UUID(), nullable=False),
        sa.Column("credit_account_id", sa.UUID(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('MANUAL', 'GRN', 'INVENTORY', 'INVOICE', 'PAYMENT', 'PAYROLL', 'DEPRECIATION', 'OPENING_BALANCE')",
            name=op.f("ck_posting_rules_source_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_posting_rules_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["credit_account_id"],
            ["accounts.id"],
            name=op.f("fk_posting_rules_credit_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["debit_account_id"],
            ["accounts.id"],
            name=op.f("fk_posting_rules_debit_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posting_rules")),
    )
    op.create_index(
        op.f("ix_posting_rules_company_id"), "posting_rules", ["company_id"], unique=False
    )
    op.create_index(
        "ix_posting_rules_lookup",
        "posting_rules",
        ["company_id", "source_type", "event", "is_active"],
        unique=False,
    )
    op.create_table(
        "budgets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'APPROVED', 'REVISED', 'CLOSED')",
            name=op.f("ck_budgets_status_valid"),
        ),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_budgets_total_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_budgets_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_budgets_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint(
            "company_id", "project_id", "fiscal_year", name="uq_budgets_project_fy"
        ),
    )
    op.create_index(op.f("ix_budgets_company_id"), "budgets", ["company_id"], unique=False)
    op.create_index(op.f("ix_budgets_project_id"), "budgets", ["project_id"], unique=False)
    op.create_table(
        "budget_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("budget_id", sa.UUID(), nullable=False),
        sa.Column("phase_id", sa.UUID(), nullable=True),
        sa.Column("cost_center_id", sa.UUID(), nullable=True),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("material_category_id", sa.UUID(), nullable=True),
        sa.Column("period_id", sa.UUID(), nullable=True),
        sa.Column("budgeted_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("revised_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("committed_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("actual_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "actual_amount >= 0", name=op.f("ck_budget_lines_actual_amount_non_negative")
        ),
        sa.CheckConstraint(
            "budgeted_amount >= 0", name=op.f("ck_budget_lines_budgeted_amount_non_negative")
        ),
        sa.CheckConstraint(
            "committed_amount >= 0", name=op.f("ck_budget_lines_committed_amount_non_negative")
        ),
        sa.CheckConstraint(
            "revised_amount IS NULL OR revised_amount >= 0",
            name=op.f("ck_budget_lines_revised_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_budget_lines_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
            name=op.f("fk_budget_lines_budget_id_budgets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cost_center_id"],
            ["cost_centers.id"],
            name=op.f("fk_budget_lines_cost_center_id_cost_centers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_category_id"],
            ["material_categories.id"],
            name=op.f("fk_budget_lines_material_category_id_material_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["accounting_periods.id"],
            name=op.f("fk_budget_lines_period_id_accounting_periods"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["project_phases.id"],
            name=op.f("fk_budget_lines_phase_id_project_phases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_lines")),
        sa.UniqueConstraint(
            "budget_id", "phase_id", "cost_center_id", "account_id", name="uq_budget_lines_scope"
        ),
    )
    op.create_index(
        op.f("ix_budget_lines_account_id"), "budget_lines", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_budget_lines_budget_id"), "budget_lines", ["budget_id"], unique=False)
    op.create_table(
        "budget_commitments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("budget_line_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("released_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "source_type IN ('PO', 'CONTRACT')",
            name=op.f("ck_budget_commitments_source_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'PARTIALLY_RELEASED', 'RELEASED', 'CANCELLED')",
            name=op.f("ck_budget_commitments_status_valid"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_budget_commitments_amount_non_negative")),
        sa.CheckConstraint(
            "released_amount <= amount",
            name=op.f("ck_budget_commitments_released_not_over_committed"),
        ),
        sa.CheckConstraint(
            "released_amount >= 0", name=op.f("ck_budget_commitments_released_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["budget_line_id"],
            ["budget_lines.id"],
            name=op.f("fk_budget_commitments_budget_line_id_budget_lines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_commitments")),
    )
    op.create_index(
        op.f("ix_budget_commitments_budget_line_id"),
        "budget_commitments",
        ["budget_line_id"],
        unique=False,
    )
    op.create_index(
        "ix_budget_commitments_source",
        "budget_commitments",
        ["source_type", "source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_budget_commitments_source", table_name="budget_commitments")
    op.drop_index(op.f("ix_budget_commitments_budget_line_id"), table_name="budget_commitments")
    op.drop_table("budget_commitments")
    op.drop_index(op.f("ix_budget_lines_budget_id"), table_name="budget_lines")
    op.drop_index(op.f("ix_budget_lines_account_id"), table_name="budget_lines")
    op.drop_table("budget_lines")
    op.drop_index(op.f("ix_budgets_project_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_company_id"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index("ix_posting_rules_lookup", table_name="posting_rules")
    op.drop_index(op.f("ix_posting_rules_company_id"), table_name="posting_rules")
    op.drop_table("posting_rules")
    # ### end Alembic commands ###
