"""sync cursor on deliveries

Revision ID: 0fa42738c500
Revises: 997ba5bd48fd
Created: 2026-09-27 05:22:43.871101+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "0fa42738c500"
down_revision: str | None = "997ba5bd48fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deliveries", sa.Column("server_seq", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_deliveries_server_seq"), "deliveries", ["server_seq"], unique=False)
    # ### end Alembic commands ###
    # A phone follows the fate of its own deliveries through the same cursor as reference data
    # (084cfc193976 created the sequence and the trigger function). Existing rows take their
    # place in the sequence, then the trigger keeps it current on every insert and update.
    op.execute("UPDATE deliveries SET server_seq = nextval('global_change_seq')")
    op.execute(
        """
        CREATE TRIGGER deliveries_server_seq
        BEFORE INSERT OR UPDATE ON deliveries
        FOR EACH ROW EXECUTE FUNCTION krb_bump_server_seq();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS deliveries_server_seq ON deliveries")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliveries_server_seq"), table_name="deliveries")
    op.drop_column("deliveries", "server_seq")
    # ### end Alembic commands ###
