"""unit conversion calibrations

Revision ID: 1df44acb8972
Revises: 323a90124451
Created: 2026-09-22 13:16:50.635435+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "1df44acb8972"
down_revision: str | None = "323a90124451"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit_conversion_calibrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("from_unit_id", sa.UUID(), nullable=False),
        sa.Column("to_unit_id", sa.UUID(), nullable=False),
        sa.Column("source_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("target_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("implied_factor", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("truck_number", sa.String(length=20), nullable=True),
        sa.Column(
            "weighbridge_ref",
            sa.String(length=80),
            nullable=True,
            comment="Weighbridge slip / docket number, for traceability",
        ),
        sa.Column("recorded_at", sa.Date(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("applied_conversion_id", sa.UUID(), nullable=True),
        sa.Column("discard_reason", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'DISCARDED' OR discard_reason IS NOT NULL",
            name=op.f("ck_unit_conversion_calibrations_discard_requires_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPLIED', 'DISCARDED')",
            name=op.f("ck_unit_conversion_calibrations_status_valid"),
        ),
        sa.CheckConstraint(
            "from_unit_id <> to_unit_id", name=op.f("ck_unit_conversion_calibrations_units_differ")
        ),
        sa.CheckConstraint(
            "implied_factor > 0",
            name=op.f("ck_unit_conversion_calibrations_implied_factor_positive"),
        ),
        sa.CheckConstraint(
            "source_quantity > 0",
            name=op.f("ck_unit_conversion_calibrations_source_quantity_positive"),
        ),
        sa.CheckConstraint(
            "target_quantity > 0",
            name=op.f("ck_unit_conversion_calibrations_target_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["applied_conversion_id"],
            ["unit_conversions.id"],
            name=op.f("fk_unit_conversion_calibrations_applied_conversion_id_unit_conversions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_unit_conversion_calibrations_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_unit_id"],
            ["units.id"],
            name=op.f("fk_unit_conversion_calibrations_from_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_unit_conversion_calibrations_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_unit_id"],
            ["units.id"],
            name=op.f("fk_unit_conversion_calibrations_to_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_unit_conversion_calibrations_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_conversion_calibrations")),
    )
    op.create_index(
        "ix_calibrations_pending",
        "unit_conversion_calibrations",
        ["company_id", "material_id", "vendor_id", "from_unit_id", "to_unit_id"],
        unique=False,
        postgresql_where="status = 'PENDING'",
    )
    op.create_index(
        op.f("ix_unit_conversion_calibrations_company_id"),
        "unit_conversion_calibrations",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unit_conversion_calibrations_deleted_at"),
        "unit_conversion_calibrations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unit_conversion_calibrations_material_id"),
        "unit_conversion_calibrations",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unit_conversion_calibrations_vendor_id"),
        "unit_conversion_calibrations",
        ["vendor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_unit_conversion_calibrations_vendor_id"), table_name="unit_conversion_calibrations"
    )
    op.drop_index(
        op.f("ix_unit_conversion_calibrations_material_id"),
        table_name="unit_conversion_calibrations",
    )
    op.drop_index(
        op.f("ix_unit_conversion_calibrations_deleted_at"),
        table_name="unit_conversion_calibrations",
    )
    op.drop_index(
        op.f("ix_unit_conversion_calibrations_company_id"),
        table_name="unit_conversion_calibrations",
    )
    op.drop_index(
        "ix_calibrations_pending",
        table_name="unit_conversion_calibrations",
        postgresql_where="status = 'PENDING'",
    )
    op.drop_table("unit_conversion_calibrations")
    # ### end Alembic commands ###
