"""vendor rates and history

Revision ID: b4cfe34224c7
Revises: 759939546f42
Created: 2026-09-26 03:50:45.249429+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b4cfe34224c7"
down_revision: str | None = "759939546f42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_rates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("previous_rate", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("change_pct", sa.Numeric(precision=9, scale=2), nullable=True),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column("approval_request_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("vendor_id"), "="),
            (sa.column("material_id"), "="),
            (sa.column("unit_id"), "="),
            (sa.text("coalesce(project_id, '00000000-0000-0000-0000-000000000000'::uuid)"), "="),
            (sa.text("coalesce(site_id, '00000000-0000-0000-0000-000000000000'::uuid)"), "="),
            (sa.text("daterange(effective_from, effective_to, '[]')"), "&&"),
            where=sa.text("status = 'ACTIVE'"),
            using="gist",
            name="ex_vendor_rates_no_overlap",
        ),
        sa.CheckConstraint(
            "source IN ('MANUAL', 'PO', 'QUOTATION')", name=op.f("ck_vendor_rates_source_valid")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING_APPROVAL', 'ACTIVE', 'REJECTED', 'WITHDRAWN')",
            name=op.f("ck_vendor_rates_status_valid"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_vendor_rates_effective_period_valid"),
        ),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_vendor_rates_rate_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendor_rates_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_vendor_rates_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_vendor_rates_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_vendor_rates_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_vendor_rates_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_rates_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_rates")),
    )
    op.create_index(
        op.f("ix_vendor_rates_company_id"), "vendor_rates", ["company_id"], unique=False
    )
    op.create_index(
        "ix_vendor_rates_lookup",
        "vendor_rates",
        ["company_id", "vendor_id", "material_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_rates_material_id"), "vendor_rates", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_rates_project_id"), "vendor_rates", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_vendor_rates_site_id"), "vendor_rates", ["site_id"], unique=False)
    op.create_index(op.f("ix_vendor_rates_vendor_id"), "vendor_rates", ["vendor_id"], unique=False)
    op.create_table(
        "vendor_rate_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vendor_rate_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("superseded_rate_id", sa.UUID(), nullable=True),
        sa.Column("old_rate", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("new_rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("change_pct", sa.Numeric(precision=9, scale=2), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("changed_by_id", sa.UUID(), nullable=True),
        sa.Column("approval_request_id", sa.UUID(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "new_rate >= 0", name=op.f("ck_vendor_rate_history_new_rate_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_rate_id"],
            ["vendor_rates.id"],
            name=op.f("fk_vendor_rate_history_vendor_rate_id_vendor_rates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_rate_history")),
    )
    op.create_index(
        op.f("ix_vendor_rate_history_company_id"),
        "vendor_rate_history",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_vendor_rate_history_lookup",
        "vendor_rate_history",
        ["company_id", "vendor_id", "material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_rate_history_material_id"),
        "vendor_rate_history",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_rate_history_vendor_id"), "vendor_rate_history", ["vendor_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_rate_history_vendor_rate_id"),
        "vendor_rate_history",
        ["vendor_rate_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    # docs/05 §4: rate history is append-only, enforced by the same trigger as
    # the audit log (function created in revision 2c50c3af7621), so not even
    # a direct UPDATE or DELETE can rewrite why a price changed.
    op.execute(
        """
        CREATE TRIGGER vendor_rate_history_append_only
        BEFORE UPDATE OR DELETE ON vendor_rate_history
        FOR EACH ROW EXECUTE FUNCTION krb_forbid_update_delete();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS vendor_rate_history_append_only ON vendor_rate_history")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendor_rate_history_vendor_rate_id"), table_name="vendor_rate_history")
    op.drop_index(op.f("ix_vendor_rate_history_vendor_id"), table_name="vendor_rate_history")
    op.drop_index(op.f("ix_vendor_rate_history_material_id"), table_name="vendor_rate_history")
    op.drop_index("ix_vendor_rate_history_lookup", table_name="vendor_rate_history")
    op.drop_index(op.f("ix_vendor_rate_history_company_id"), table_name="vendor_rate_history")
    op.drop_table("vendor_rate_history")
    op.drop_index(op.f("ix_vendor_rates_vendor_id"), table_name="vendor_rates")
    op.drop_index(op.f("ix_vendor_rates_site_id"), table_name="vendor_rates")
    op.drop_index(op.f("ix_vendor_rates_project_id"), table_name="vendor_rates")
    op.drop_index(op.f("ix_vendor_rates_material_id"), table_name="vendor_rates")
    op.drop_index("ix_vendor_rates_lookup", table_name="vendor_rates")
    op.drop_index(op.f("ix_vendor_rates_company_id"), table_name="vendor_rates")
    op.drop_table("vendor_rates")
    # ### end Alembic commands ###
