"""master data and vendors

Revision ID: 323a90124451
Revises: 2c50c3af7621
Created: 2026-09-22 02:09:26.118365+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "323a90124451"
down_revision: str | None = "2c50c3af7621"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("parent_id <> id", name=op.f("ck_material_categories_no_self_parent")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_material_categories_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["material_categories.id"],
            name=op.f("fk_material_categories_parent_id_material_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_categories")),
        sa.UniqueConstraint("company_id", "code", name="uq_material_categories_company_id_code"),
    )
    op.create_index(
        op.f("ix_material_categories_company_id"),
        "material_categories",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_categories_deleted_at"),
        "material_categories",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_categories_parent_id"), "material_categories", ["parent_id"], unique=False
    )
    op.create_table(
        "truck_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("axle_count", sa.SmallInteger(), nullable=True),
        sa.Column("default_max_tonnage", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("typical_volume_cft", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "default_max_tonnage > 0", name=op.f("ck_truck_types_default_max_tonnage_positive")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_truck_types_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_truck_types")),
        sa.UniqueConstraint("company_id", "code", name="uq_truck_types_company_id_code"),
    )
    op.create_index(op.f("ix_truck_types_company_id"), "truck_types", ["company_id"], unique=False)
    op.create_index(op.f("ix_truck_types_deleted_at"), "truck_types", ["deleted_at"], unique=False)
    op.create_table(
        "units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("symbol", sa.String(length=12), nullable=True),
        sa.Column("dimension", sa.String(length=20), nullable=False),
        sa.Column("precision", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "dimension IN ('MASS', 'VOLUME', 'LENGTH', 'AREA', 'COUNT', 'TIME')",
            name=op.f("ck_units_dimension_valid"),
        ),
        sa.CheckConstraint("precision BETWEEN 0 AND 6", name=op.f("ck_units_precision_range")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_units_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("company_id", "code", name="uq_units_company_id_code"),
    )
    op.create_index(op.f("ix_units_company_id"), "units", ["company_id"], unique=False)
    op.create_index(op.f("ix_units_deleted_at"), "units", ["deleted_at"], unique=False)
    op.create_table(
        "materials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("base_unit_id", sa.UUID(), nullable=False),
        sa.Column("tracking_type", sa.String(length=20), nullable=False),
        sa.Column("min_stock", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("max_stock", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("reorder_level", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("standard_rate", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("standard_rate_unit_id", sa.UUID(), nullable=True),
        sa.Column("hs_code", sa.String(length=20), nullable=True),
        sa.Column("default_tax_code", sa.String(length=20), nullable=True),
        sa.Column("is_stockable", sa.Boolean(), nullable=False),
        sa.Column("is_purchasable", sa.Boolean(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "tracking_type IN ('QUANTITY', 'BATCH', 'SERIAL')",
            name=op.f("ck_materials_tracking_type_valid"),
        ),
        sa.CheckConstraint(
            "max_stock IS NULL OR min_stock IS NULL OR max_stock >= min_stock",
            name=op.f("ck_materials_stock_bounds_ordered"),
        ),
        sa.CheckConstraint(
            "min_stock IS NULL OR min_stock >= 0", name=op.f("ck_materials_min_stock_non_negative")
        ),
        sa.CheckConstraint(
            "standard_rate IS NULL OR standard_rate >= 0",
            name=op.f("ck_materials_standard_rate_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["base_unit_id"],
            ["units.id"],
            name=op.f("fk_materials_base_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["material_categories.id"],
            name=op.f("fk_materials_category_id_material_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_materials_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["standard_rate_unit_id"],
            ["units.id"],
            name=op.f("fk_materials_standard_rate_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("company_id", "sku", name="uq_materials_company_id_sku"),
    )
    op.create_index(op.f("ix_materials_category_id"), "materials", ["category_id"], unique=False)
    op.create_index(op.f("ix_materials_company_id"), "materials", ["company_id"], unique=False)
    op.create_index(
        "ix_materials_company_id_category_id",
        "materials",
        ["company_id", "category_id"],
        unique=False,
    )
    op.create_index(op.f("ix_materials_deleted_at"), "materials", ["deleted_at"], unique=False)
    op.create_index(
        "ix_materials_name_trgm",
        "materials",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_materials_sku_trgm",
        "materials",
        ["sku"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"sku": "gin_trgm_ops"},
    )
    op.create_table(
        "vendors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("trade_name", sa.String(length=200), nullable=True),
        sa.Column("vendor_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("ntn", sa.String(length=20), nullable=True, comment="National Tax Number"),
        sa.Column(
            "strn", sa.String(length=20), nullable=True, comment="Sales Tax Registration Number"
        ),
        sa.Column(
            "cnic", sa.String(length=20), nullable=True, comment="For a sole proprietor with no NTN"
        ),
        sa.Column(
            "is_filer",
            sa.Boolean(),
            nullable=True,
            comment="FBR active-taxpayer status; drives the withholding rate",
        ),
        sa.Column("withholding_exempt", sa.Boolean(), nullable=False),
        sa.Column("withholding_certificate_ref", sa.String(length=80), nullable=True),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("credit_limit", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("website", sa.String(length=200), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspension_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'BLACKLISTED', 'INACTIVE')",
            name=op.f("ck_vendors_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('SUSPENDED', 'BLACKLISTED') OR suspension_reason IS NOT NULL",
            name=op.f("ck_vendors_suspension_requires_reason"),
        ),
        sa.CheckConstraint(
            "vendor_type IN ('MATERIAL_SUPPLIER', 'CONTRACTOR', 'SUBCONTRACTOR', 'TRANSPORTER', 'SERVICE_PROVIDER', 'CONSULTANT', 'EQUIPMENT_RENTAL')",
            name=op.f("ck_vendors_vendor_type_valid"),
        ),
        sa.CheckConstraint(
            "credit_limit IS NULL OR credit_limit >= 0",
            name=op.f("ck_vendors_credit_limit_non_negative"),
        ),
        sa.CheckConstraint(
            "payment_terms_days >= 0", name=op.f("ck_vendors_payment_terms_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_vendors_approved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendors_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
        sa.UniqueConstraint("company_id", "code", name="uq_vendors_company_id_code"),
    )
    op.create_index(op.f("ix_vendors_company_id"), "vendors", ["company_id"], unique=False)
    op.create_index(
        "ix_vendors_company_id_status", "vendors", ["company_id", "status"], unique=False
    )
    op.create_index(op.f("ix_vendors_deleted_at"), "vendors", ["deleted_at"], unique=False)
    op.create_index(
        "ix_vendors_legal_name_trgm",
        "vendors",
        ["legal_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"legal_name": "gin_trgm_ops"},
    )
    op.create_table(
        "material_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("is_purchase_default", sa.Boolean(), nullable=False),
        sa.Column("is_issue_default", sa.Boolean(), nullable=False),
        sa.Column(
            "is_capture_default",
            sa.Boolean(),
            nullable=False,
            comment="Pre-selected on the mobile delivery form",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_material_units_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_units_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_material_units_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_units")),
        sa.UniqueConstraint("material_id", "unit_id", name="uq_material_units_material_id_unit_id"),
    )
    op.create_index(
        op.f("ix_material_units_company_id"), "material_units", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_material_units_deleted_at"), "material_units", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_material_units_material_id"), "material_units", ["material_id"], unique=False
    )
    op.create_index(
        "uq_material_units_capture_default",
        "material_units",
        ["material_id"],
        unique=True,
        postgresql_where="is_capture_default",
    )
    op.create_index(
        "uq_material_units_purchase_default",
        "material_units",
        ["material_id"],
        unique=True,
        postgresql_where="is_purchase_default",
    )
    op.create_table(
        "unit_conversions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("from_unit_id", sa.UUID(), nullable=False),
        sa.Column("to_unit_id", sa.UUID(), nullable=False),
        sa.Column("factor", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("basis_note", sa.String(length=500), nullable=True),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(scope_type = 'GLOBAL' AND material_id IS NULL AND vendor_id IS NULL) OR (scope_type = 'MATERIAL' AND material_id IS NOT NULL AND vendor_id IS NULL) OR (scope_type = 'VENDOR' AND vendor_id IS NOT NULL AND material_id IS NULL) OR (scope_type = 'MATERIAL_VENDOR'     AND material_id IS NOT NULL AND vendor_id IS NOT NULL)",
            name=op.f("ck_unit_conversions_scope_columns_match_scope_type"),
        ),
        sa.CheckConstraint(
            "scope_type IN ('GLOBAL', 'MATERIAL', 'VENDOR', 'MATERIAL_VENDOR')",
            name=op.f("ck_unit_conversions_scope_type_valid"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_unit_conversions_effective_dates_ordered"),
        ),
        sa.CheckConstraint("factor > 0", name=op.f("ck_unit_conversions_factor_positive")),
        sa.CheckConstraint(
            "from_unit_id <> to_unit_id", name=op.f("ck_unit_conversions_units_differ")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_unit_conversions_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_unit_id"],
            ["units.id"],
            name=op.f("fk_unit_conversions_from_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_unit_conversions_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["unit_conversions.id"],
            name=op.f("fk_unit_conversions_supersedes_id_unit_conversions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_unit_id"],
            ["units.id"],
            name=op.f("fk_unit_conversions_to_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_unit_conversions_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_conversions")),
    )
    op.create_index(
        op.f("ix_unit_conversions_company_id"), "unit_conversions", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_unit_conversions_deleted_at"), "unit_conversions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_unit_conversions_material_id"), "unit_conversions", ["material_id"], unique=False
    )
    op.create_index(
        "ix_unit_conversions_material_scope",
        "unit_conversions",
        ["material_id", "vendor_id"],
        unique=False,
    )
    op.create_index(
        "ix_unit_conversions_resolution",
        "unit_conversions",
        ["company_id", "from_unit_id", "to_unit_id", "scope_type", "effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unit_conversions_vendor_id"), "unit_conversions", ["vendor_id"], unique=False
    )
    op.create_table(
        "vendor_bank_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("account_title", sa.String(length=200), nullable=False),
        sa.Column("account_no", sa.String(length=40), nullable=True),
        sa.Column("iban", sa.String(length=34), nullable=True),
        sa.Column("bank_name", sa.String(length=160), nullable=False),
        sa.Column("branch_name", sa.String(length=160), nullable=True),
        sa.Column("branch_code", sa.String(length=20), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by_id", sa.UUID(), nullable=True),
        sa.Column("verification_note", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "account_no IS NOT NULL OR iban IS NOT NULL",
            name=op.f("ck_vendor_bank_accounts_account_no_or_iban_required"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendor_bank_accounts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_bank_accounts_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["users.id"],
            name=op.f("fk_vendor_bank_accounts_verified_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_bank_accounts")),
    )
    op.create_index(
        op.f("ix_vendor_bank_accounts_company_id"),
        "vendor_bank_accounts",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_bank_accounts_deleted_at"),
        "vendor_bank_accounts",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_bank_accounts_vendor_id"),
        "vendor_bank_accounts",
        ["vendor_id"],
        unique=False,
    )
    op.create_index(
        "uq_vendor_bank_accounts_primary",
        "vendor_bank_accounts",
        ["vendor_id"],
        unique=True,
        postgresql_where="is_primary AND deleted_at IS NULL",
    )
    op.create_table(
        "vendor_contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("designation", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("alternate_phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "phone IS NOT NULL OR email IS NOT NULL",
            name=op.f("ck_vendor_contacts_phone_or_email_required"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendor_contacts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_contacts_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_contacts")),
    )
    op.create_index(
        op.f("ix_vendor_contacts_company_id"), "vendor_contacts", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_contacts_deleted_at"), "vendor_contacts", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_contacts_vendor_id"), "vendor_contacts", ["vendor_id"], unique=False
    )
    op.create_index(
        "uq_vendor_contacts_primary",
        "vendor_contacts",
        ["vendor_id"],
        unique=True,
        postgresql_where="is_primary AND deleted_at IS NULL",
    )
    op.create_table(
        "vendor_materials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("lead_time_days", sa.SmallInteger(), nullable=True),
        sa.Column("min_order_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "vendor_material_code",
            sa.String(length=60),
            nullable=True,
            comment="The vendor's own code, for matching their challans",
        ),
        sa.Column("is_preferred", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "min_order_quantity IS NULL OR min_order_quantity > 0",
            name=op.f("ck_vendor_materials_min_order_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendor_materials_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_vendor_materials_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_materials_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_materials")),
        sa.UniqueConstraint(
            "vendor_id", "material_id", name="uq_vendor_materials_vendor_id_material_id"
        ),
    )
    op.create_index(
        op.f("ix_vendor_materials_company_id"), "vendor_materials", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_materials_deleted_at"), "vendor_materials", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_materials_material_id"), "vendor_materials", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_materials_vendor_id"), "vendor_materials", ["vendor_id"], unique=False
    )
    op.create_table(
        "vendor_performance_facts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column(
            "period_month",
            sa.Date(),
            nullable=False,
            comment="First day of the month the facts cover",
        ),
        sa.Column("deliveries_count", sa.Integer(), nullable=False),
        sa.Column("on_time_count", sa.Integer(), nullable=False),
        sa.Column("late_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("flagged_count", sa.Integer(), nullable=False),
        sa.Column("ordered_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("delivered_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("accepted_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("purchase_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quality_incidents", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "deliveries_count >= 0",
            name=op.f("ck_vendor_performance_facts_deliveries_count_non_negative"),
        ),
        sa.CheckConstraint(
            "on_time_count + late_count <= deliveries_count",
            name=op.f("ck_vendor_performance_facts_timing_counts_consistent"),
        ),
        sa.CheckConstraint(
            "rejected_count >= 0",
            name=op.f("ck_vendor_performance_facts_rejected_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendor_performance_facts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_performance_facts_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_performance_facts")),
        sa.UniqueConstraint(
            "vendor_id", "period_month", name="uq_vendor_performance_facts_vendor_id_period"
        ),
    )
    op.create_index(
        op.f("ix_vendor_performance_facts_company_id"),
        "vendor_performance_facts",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_vendor_performance_facts_period",
        "vendor_performance_facts",
        ["company_id", "period_month"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_performance_facts_vendor_id"),
        "vendor_performance_facts",
        ["vendor_id"],
        unique=False,
    )
    op.create_table(
        "warehouses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("warehouse_type", sa.String(length=20), nullable=False),
        sa.Column("keeper_user_id", sa.UUID(), nullable=True),
        sa.Column("is_default_receiving", sa.Boolean(), nullable=False),
        sa.Column("capacity_note", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "warehouse_type IN ('SITE_STORE', 'CENTRAL', 'TRANSIT', 'QUARANTINE')",
            name=op.f("ck_warehouses_warehouse_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_warehouses_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["keeper_user_id"],
            ["users.id"],
            name=op.f("fk_warehouses_keeper_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_warehouses_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("company_id", "code", name="uq_warehouses_company_id_code"),
    )
    op.create_index(op.f("ix_warehouses_company_id"), "warehouses", ["company_id"], unique=False)
    op.create_index(op.f("ix_warehouses_deleted_at"), "warehouses", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_warehouses_site_id"), "warehouses", ["site_id"], unique=False)
    op.create_index(
        "uq_warehouses_default_receiving",
        "warehouses",
        ["site_id"],
        unique=True,
        postgresql_where="is_default_receiving",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_warehouses_default_receiving",
        table_name="warehouses",
        postgresql_where="is_default_receiving",
    )
    op.drop_index(op.f("ix_warehouses_site_id"), table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_deleted_at"), table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_company_id"), table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_index(
        op.f("ix_vendor_performance_facts_vendor_id"), table_name="vendor_performance_facts"
    )
    op.drop_index("ix_vendor_performance_facts_period", table_name="vendor_performance_facts")
    op.drop_index(
        op.f("ix_vendor_performance_facts_company_id"), table_name="vendor_performance_facts"
    )
    op.drop_table("vendor_performance_facts")
    op.drop_index(op.f("ix_vendor_materials_vendor_id"), table_name="vendor_materials")
    op.drop_index(op.f("ix_vendor_materials_material_id"), table_name="vendor_materials")
    op.drop_index(op.f("ix_vendor_materials_deleted_at"), table_name="vendor_materials")
    op.drop_index(op.f("ix_vendor_materials_company_id"), table_name="vendor_materials")
    op.drop_table("vendor_materials")
    op.drop_index(
        "uq_vendor_contacts_primary",
        table_name="vendor_contacts",
        postgresql_where="is_primary AND deleted_at IS NULL",
    )
    op.drop_index(op.f("ix_vendor_contacts_vendor_id"), table_name="vendor_contacts")
    op.drop_index(op.f("ix_vendor_contacts_deleted_at"), table_name="vendor_contacts")
    op.drop_index(op.f("ix_vendor_contacts_company_id"), table_name="vendor_contacts")
    op.drop_table("vendor_contacts")
    op.drop_index(
        "uq_vendor_bank_accounts_primary",
        table_name="vendor_bank_accounts",
        postgresql_where="is_primary AND deleted_at IS NULL",
    )
    op.drop_index(op.f("ix_vendor_bank_accounts_vendor_id"), table_name="vendor_bank_accounts")
    op.drop_index(op.f("ix_vendor_bank_accounts_deleted_at"), table_name="vendor_bank_accounts")
    op.drop_index(op.f("ix_vendor_bank_accounts_company_id"), table_name="vendor_bank_accounts")
    op.drop_table("vendor_bank_accounts")
    op.drop_index(op.f("ix_unit_conversions_vendor_id"), table_name="unit_conversions")
    op.drop_index("ix_unit_conversions_resolution", table_name="unit_conversions")
    op.drop_index("ix_unit_conversions_material_scope", table_name="unit_conversions")
    op.drop_index(op.f("ix_unit_conversions_material_id"), table_name="unit_conversions")
    op.drop_index(op.f("ix_unit_conversions_deleted_at"), table_name="unit_conversions")
    op.drop_index(op.f("ix_unit_conversions_company_id"), table_name="unit_conversions")
    op.drop_table("unit_conversions")
    op.drop_index(
        "uq_material_units_purchase_default",
        table_name="material_units",
        postgresql_where="is_purchase_default",
    )
    op.drop_index(
        "uq_material_units_capture_default",
        table_name="material_units",
        postgresql_where="is_capture_default",
    )
    op.drop_index(op.f("ix_material_units_material_id"), table_name="material_units")
    op.drop_index(op.f("ix_material_units_deleted_at"), table_name="material_units")
    op.drop_index(op.f("ix_material_units_company_id"), table_name="material_units")
    op.drop_table("material_units")
    op.drop_index(
        "ix_vendors_legal_name_trgm",
        table_name="vendors",
        postgresql_using="gin",
        postgresql_ops={"legal_name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_vendors_deleted_at"), table_name="vendors")
    op.drop_index("ix_vendors_company_id_status", table_name="vendors")
    op.drop_index(op.f("ix_vendors_company_id"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(
        "ix_materials_sku_trgm",
        table_name="materials",
        postgresql_using="gin",
        postgresql_ops={"sku": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_materials_name_trgm",
        table_name="materials",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_materials_deleted_at"), table_name="materials")
    op.drop_index("ix_materials_company_id_category_id", table_name="materials")
    op.drop_index(op.f("ix_materials_company_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_category_id"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(op.f("ix_units_deleted_at"), table_name="units")
    op.drop_index(op.f("ix_units_company_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_truck_types_deleted_at"), table_name="truck_types")
    op.drop_index(op.f("ix_truck_types_company_id"), table_name="truck_types")
    op.drop_table("truck_types")
    op.drop_index(op.f("ix_material_categories_parent_id"), table_name="material_categories")
    op.drop_index(op.f("ix_material_categories_deleted_at"), table_name="material_categories")
    op.drop_index(op.f("ix_material_categories_company_id"), table_name="material_categories")
    op.drop_table("material_categories")
    # ### end Alembic commands ###
