"""inventory ledger and goods received notes

Revision ID: af8136a03a41
Revises: d91a3882f18a
Created: 2026-09-26 04:37:07.508202+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "af8136a03a41"
down_revision: str | None = "d91a3882f18a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_balances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("quantity_on_hand", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quantity_reserved", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quantity_in_transit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("last_transaction_id", sa.UUID(), nullable=True),
        sa.Column("last_movement_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "quantity_on_hand >= 0",
            name=op.f("ck_inventory_balances_quantity_on_hand_non_negative"),
        ),
        sa.CheckConstraint(
            "total_value >= 0", name=op.f("ck_inventory_balances_total_value_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_inventory_balances_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_inventory_balances_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_balances_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_balances")),
        sa.UniqueConstraint("warehouse_id", "material_id", name="uq_inventory_balances_stock"),
    )
    op.create_index(
        op.f("ix_inventory_balances_company_id"), "inventory_balances", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_balances_material_id"),
        "inventory_balances",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_project_id"), "inventory_balances", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_balances_site_id"), "inventory_balances", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_balances_warehouse_id"),
        "inventory_balances",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("txn_type", sa.String(length=20), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("quantity_in", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("quantity_out", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("value_in", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("value_out", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("balance_quantity_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("balance_value_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_line_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("cost_center_id", sa.UUID(), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reversal_of_id", sa.UUID(), nullable=True),
        sa.Column("remarks", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "txn_type IN ('GRN_IN', 'ISSUE_OUT', 'TRANSFER_OUT', 'TRANSFER_IN', 'ADJUST_IN', 'ADJUST_OUT', 'RETURN_IN', 'RETURN_OUT', 'REVERSAL_IN', 'REVERSAL_OUT')",
            name=op.f("ck_inventory_transactions_txn_type_valid"),
        ),
        sa.CheckConstraint(
            "(quantity_in > 0 AND quantity_out = 0) OR (quantity_out > 0 AND quantity_in = 0)",
            name=op.f("ck_inventory_transactions_moves_one_way"),
        ),
        sa.CheckConstraint(
            "balance_quantity_after >= 0",
            name=op.f("ck_inventory_transactions_balance_quantity_after_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity_in >= 0", name=op.f("ck_inventory_transactions_quantity_in_non_negative")
        ),
        sa.CheckConstraint(
            "quantity_out >= 0", name=op.f("ck_inventory_transactions_quantity_out_non_negative")
        ),
        sa.CheckConstraint(
            "value_in >= 0", name=op.f("ck_inventory_transactions_value_in_non_negative")
        ),
        sa.CheckConstraint(
            "value_out >= 0", name=op.f("ck_inventory_transactions_value_out_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_inventory_transactions_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_inventory_transactions_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_transactions_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_transactions")),
    )
    op.create_index(
        op.f("ix_inventory_transactions_company_id"),
        "inventory_transactions",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_material_id"),
        "inventory_transactions",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_project_id"),
        "inventory_transactions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_site_id"),
        "inventory_transactions",
        ["site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_source_id"),
        "inventory_transactions",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_transactions_stock",
        "inventory_transactions",
        ["warehouse_id", "material_id", "posted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_warehouse_id"),
        "inventory_transactions",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "grns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("grn_number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=True),
        sa.Column("purchase_order_id", sa.UUID(), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column("inspection_result", sa.String(length=10), nullable=False),
        sa.Column("inspected_by_id", sa.UUID(), nullable=True),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by_id", sa.UUID(), nullable=True),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "inspection_result IN ('PENDING', 'PASSED', 'FAILED', 'PARTIAL')",
            name=op.f("ck_grns_inspection_result_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR cancel_reason IS NOT NULL",
            name=op.f("ck_grns_cancel_needs_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'POSTED', 'CANCELLED')", name=op.f("ck_grns_status_valid")
        ),
        sa.CheckConstraint("gross_amount >= 0", name=op.f("ck_grns_gross_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_grns_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_grns_delivery_id_deliveries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_grns_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_grns_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_grns_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_grns_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_grns_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grns")),
        sa.UniqueConstraint("company_id", "grn_number", name="uq_grns_number"),
    )
    op.create_index(op.f("ix_grns_company_id"), "grns", ["company_id"], unique=False)
    op.create_index(op.f("ix_grns_delivery_id"), "grns", ["delivery_id"], unique=False)
    op.create_index(op.f("ix_grns_project_id"), "grns", ["project_id"], unique=False)
    op.create_index(op.f("ix_grns_purchase_order_id"), "grns", ["purchase_order_id"], unique=False)
    op.create_index(op.f("ix_grns_site_id"), "grns", ["site_id"], unique=False)
    op.create_index(op.f("ix_grns_vendor_id"), "grns", ["vendor_id"], unique=False)
    op.create_index(
        "uq_grns_live_delivery",
        "grns",
        ["delivery_id"],
        unique=True,
        postgresql_where="status <> 'CANCELLED' AND delivery_id IS NOT NULL",
    )
    op.create_table(
        "grn_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("grn_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("po_item_id", sa.UUID(), nullable=True),
        sa.Column("delivery_item_id", sa.UUID(), nullable=True),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("ordered_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("delivered_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("accepted_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("rejected_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("rejection_reason", sa.String(length=300), nullable=True),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("vendor_rate_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("base_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("inventory_txn_id", sa.UUID(), nullable=True),
        sa.Column("batch_no", sa.String(length=60), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "accepted_quantity + rejected_quantity = delivered_quantity",
            name=op.f("ck_grn_items_accepted_plus_rejected_equals_delivered"),
        ),
        sa.CheckConstraint(
            "accepted_quantity >= 0", name=op.f("ck_grn_items_accepted_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "delivered_quantity >= 0", name=op.f("ck_grn_items_delivered_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "rejected_quantity = 0 OR rejection_reason IS NOT NULL",
            name=op.f("ck_grn_items_rejection_needs_reason"),
        ),
        sa.CheckConstraint(
            "rejected_quantity >= 0", name=op.f("ck_grn_items_rejected_quantity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["delivery_item_id"],
            ["delivery_items.id"],
            name=op.f("fk_grn_items_delivery_item_id_delivery_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grn_id"], ["grns.id"], name=op.f("fk_grn_items_grn_id_grns"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_grn_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["po_item_id"],
            ["purchase_order_items.id"],
            name=op.f("fk_grn_items_po_item_id_purchase_order_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_grn_items_unit_id_units"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grn_items")),
        sa.UniqueConstraint("grn_id", "line_no", name="uq_grn_items_line"),
    )
    op.create_index(op.f("ix_grn_items_grn_id"), "grn_items", ["grn_id"], unique=False)
    op.create_index(op.f("ix_grn_items_material_id"), "grn_items", ["material_id"], unique=False)
    # ### end Alembic commands ###
    # docs/02 §7: the stock ledger is append-only, enforced by the same trigger
    # as the audit log (function created in revision 2c50c3af7621). A mistake is
    # put right with a contra row, never an edit.
    op.execute(
        """
        CREATE TRIGGER inventory_transactions_append_only
        BEFORE UPDATE OR DELETE ON inventory_transactions
        FOR EACH ROW EXECUTE FUNCTION krb_forbid_update_delete();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS inventory_transactions_append_only ON inventory_transactions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grn_items_material_id"), table_name="grn_items")
    op.drop_index(op.f("ix_grn_items_grn_id"), table_name="grn_items")
    op.drop_table("grn_items")
    op.drop_index(
        "uq_grns_live_delivery",
        table_name="grns",
        postgresql_where="status <> 'CANCELLED' AND delivery_id IS NOT NULL",
    )
    op.drop_index(op.f("ix_grns_vendor_id"), table_name="grns")
    op.drop_index(op.f("ix_grns_site_id"), table_name="grns")
    op.drop_index(op.f("ix_grns_purchase_order_id"), table_name="grns")
    op.drop_index(op.f("ix_grns_project_id"), table_name="grns")
    op.drop_index(op.f("ix_grns_delivery_id"), table_name="grns")
    op.drop_index(op.f("ix_grns_company_id"), table_name="grns")
    op.drop_table("grns")
    op.drop_index(
        op.f("ix_inventory_transactions_warehouse_id"), table_name="inventory_transactions"
    )
    op.drop_index("ix_inventory_transactions_stock", table_name="inventory_transactions")
    op.drop_index(op.f("ix_inventory_transactions_source_id"), table_name="inventory_transactions")
    op.drop_index(op.f("ix_inventory_transactions_site_id"), table_name="inventory_transactions")
    op.drop_index(op.f("ix_inventory_transactions_project_id"), table_name="inventory_transactions")
    op.drop_index(
        op.f("ix_inventory_transactions_material_id"), table_name="inventory_transactions"
    )
    op.drop_index(op.f("ix_inventory_transactions_company_id"), table_name="inventory_transactions")
    op.drop_table("inventory_transactions")
    op.drop_index(op.f("ix_inventory_balances_warehouse_id"), table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_site_id"), table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_project_id"), table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_material_id"), table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_company_id"), table_name="inventory_balances")
    op.drop_table("inventory_balances")
    # ### end Alembic commands ###
