"""deliveries

Revision ID: d91a3882f18a
Revises: b4cfe34224c7
Created: 2026-09-26 04:18:48.833524+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d91a3882f18a"
down_revision: str | None = "b4cfe34224c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("delivery_number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("purchase_order_id", sa.UUID(), nullable=True),
        sa.Column("po_item_id", sa.UUID(), nullable=True),
        sa.Column("truck_number", sa.String(length=30), nullable=True),
        sa.Column("truck_type_id", sa.UUID(), nullable=True),
        sa.Column("driver_name", sa.String(length=120), nullable=True),
        sa.Column("driver_phone", sa.String(length=32), nullable=True),
        sa.Column("challan_number", sa.String(length=60), nullable=True),
        sa.Column("challan_date", sa.Date(), nullable=True),
        sa.Column("captured_lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("captured_lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column(
            "captured_point",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("gps_accuracy_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("location_source", sa.String(length=10), nullable=False),
        sa.Column("distance_from_site_m", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_inside_geofence", sa.Boolean(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("clock_skew_seconds", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.String(length=80), nullable=True),
        sa.Column("app_version", sa.String(length=30), nullable=True),
        sa.Column("was_offline", sa.Boolean(), nullable=False),
        sa.Column("submitted_by_id", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by_id", sa.UUID(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.Column("flag_count", sa.Integer(), nullable=False),
        sa.Column("has_open_flags", sa.Boolean(), nullable=False),
        sa.Column("grn_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "location_source IN ('GPS', 'NETWORK', 'MANUAL')",
            name=op.f("ck_deliveries_location_source_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'REJECTED' OR rejection_reason IS NOT NULL",
            name=op.f("ck_deliveries_rejection_needs_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'CORRECTION_REQUESTED', 'APPROVED', 'REJECTED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')",
            name=op.f("ck_deliveries_status_valid"),
        ),
        sa.CheckConstraint("flag_count >= 0", name=op.f("ck_deliveries_flag_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_deliveries_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["po_item_id"],
            ["purchase_order_items.id"],
            name=op.f("fk_deliveries_po_item_id_purchase_order_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_deliveries_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_deliveries_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_deliveries_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["truck_type_id"],
            ["truck_types.id"],
            name=op.f("fk_deliveries_truck_type_id_truck_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_deliveries_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("company_id", "delivery_number", name="uq_deliveries_number"),
    )
    op.create_index(op.f("ix_deliveries_company_id"), "deliveries", ["company_id"], unique=False)
    op.create_index(op.f("ix_deliveries_project_id"), "deliveries", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_deliveries_purchase_order_id"), "deliveries", ["purchase_order_id"], unique=False
    )
    op.create_index(
        "ix_deliveries_review_queue",
        "deliveries",
        ["company_id", "status"],
        unique=False,
        postgresql_where=sa.text("has_open_flags"),
    )
    op.create_index(
        "ix_deliveries_site_captured",
        "deliveries",
        ["company_id", "site_id", "captured_at"],
        unique=False,
    )
    op.create_index(op.f("ix_deliveries_site_id"), "deliveries", ["site_id"], unique=False)
    op.create_index(
        "ix_deliveries_vendor_captured", "deliveries", ["vendor_id", "captured_at"], unique=False
    )
    op.create_index(op.f("ix_deliveries_vendor_id"), "deliveries", ["vendor_id"], unique=False)
    op.create_table(
        "delivery_flags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("flag_type", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("rule_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("actual_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("deviation_pct", sa.Numeric(precision=9, scale=2), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("resolved_by_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "flag_type IN ('TONNAGE_ANOMALY', 'GEOFENCE_MISMATCH', 'CLOCK_SKEW', 'DUPLICATE_SUSPECT', 'NO_PO', 'PO_QTY_EXCEEDED', 'DAILY_CAP_EXCEEDED', 'RATE_MISSING', 'CONVERSION_MISSING', 'VENDOR_INACTIVE', 'LATE_SUBMISSION')",
            name=op.f("ck_delivery_flags_flag_type_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('INFO', 'WARNING', 'CRITICAL')",
            name=op.f("ck_delivery_flags_severity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'ACCEPTED', 'REJECTED', 'CORRECTED', 'WAIVED')",
            name=op.f("ck_delivery_flags_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_delivery_flags_delivery_id_deliveries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_flags")),
    )
    op.create_index(
        op.f("ix_delivery_flags_delivery_id"), "delivery_flags", ["delivery_id"], unique=False
    )
    op.create_index(
        "ix_delivery_flags_open", "delivery_flags", ["delivery_id", "status"], unique=False
    )
    op.create_table(
        "delivery_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("converted_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("converted_unit_id", sa.UUID(), nullable=True),
        sa.Column("conversion_factor", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("conversion_id", sa.UUID(), nullable=True),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("vendor_rate_id", sa.UUID(), nullable=True),
        sa.Column("rate_source", sa.String(length=12), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("po_item_id", sa.UUID(), nullable=True),
        sa.Column("remarks", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "amount IS NULL OR amount >= 0", name=op.f("ck_delivery_items_amount_non_negative")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_delivery_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["converted_unit_id"],
            ["units.id"],
            name=op.f("fk_delivery_items_converted_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_delivery_items_delivery_id_deliveries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_delivery_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["po_item_id"],
            ["purchase_order_items.id"],
            name=op.f("fk_delivery_items_po_item_id_purchase_order_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_delivery_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_items")),
        sa.UniqueConstraint("delivery_id", "line_no", name="uq_delivery_items_line"),
    )
    op.create_index(
        op.f("ix_delivery_items_delivery_id"), "delivery_items", ["delivery_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_items_material_id"), "delivery_items", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_items_po_item_id"), "delivery_items", ["po_item_id"], unique=False
    )
    op.create_table(
        "delivery_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("reviewer_name", sa.String(length=160), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("comments", sa.String(length=1000), nullable=True),
        sa.Column("corrected_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("previous_status", sa.String(length=30), nullable=False),
        sa.Column("new_status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "action IN ('ACCEPT', 'REJECT', 'REQUEST_CORRECTION', 'CORRECTION_SUBMITTED', 'REOPEN', 'ATTACH_PO')",
            name=op.f("ck_delivery_reviews_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_delivery_reviews_delivery_id_deliveries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_reviews")),
    )
    op.create_index(
        op.f("ix_delivery_reviews_company_id"), "delivery_reviews", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_reviews_delivery_id"), "delivery_reviews", ["delivery_id"], unique=False
    )
    # ### end Alembic commands ###
    # docs/02 §6: review decisions are append-only, enforced by the same trigger
    # as the audit log (function created in revision 2c50c3af7621).
    op.execute(
        """
        CREATE TRIGGER delivery_reviews_append_only
        BEFORE UPDATE OR DELETE ON delivery_reviews
        FOR EACH ROW EXECUTE FUNCTION krb_forbid_update_delete();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS delivery_reviews_append_only ON delivery_reviews")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_reviews_delivery_id"), table_name="delivery_reviews")
    op.drop_index(op.f("ix_delivery_reviews_company_id"), table_name="delivery_reviews")
    op.drop_table("delivery_reviews")
    op.drop_index(op.f("ix_delivery_items_po_item_id"), table_name="delivery_items")
    op.drop_index(op.f("ix_delivery_items_material_id"), table_name="delivery_items")
    op.drop_index(op.f("ix_delivery_items_delivery_id"), table_name="delivery_items")
    op.drop_table("delivery_items")
    op.drop_index("ix_delivery_flags_open", table_name="delivery_flags")
    op.drop_index(op.f("ix_delivery_flags_delivery_id"), table_name="delivery_flags")
    op.drop_table("delivery_flags")
    op.drop_index(op.f("ix_deliveries_vendor_id"), table_name="deliveries")
    op.drop_index("ix_deliveries_vendor_captured", table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_site_id"), table_name="deliveries")
    op.drop_index("ix_deliveries_site_captured", table_name="deliveries")
    op.drop_index(
        "ix_deliveries_review_queue",
        table_name="deliveries",
        postgresql_where=sa.text("has_open_flags"),
    )
    op.drop_index(op.f("ix_deliveries_purchase_order_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_project_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_company_id"), table_name="deliveries")
    op.drop_table("deliveries")
    # ### end Alembic commands ###
