"""approval sla reminder markers

Revision ID: 0b818b783b15
Revises: 06cad11c4e5d
Created: 2026-09-25 18:06:43.556847+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "0b818b783b15"
down_revision: str | None = "06cad11c4e5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "approval_request_steps",
        sa.Column("reminded_50_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "approval_request_steps",
        sa.Column("reminded_90_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("approval_request_steps", "reminded_90_at")
    op.drop_column("approval_request_steps", "reminded_50_at")
    # ### end Alembic commands ###
