"""chart of accounts, periods, journal entries

Revision ID: 0c54c70e130b
Revises: 0fa42738c500
Created: 2026-09-27 06:57:40.749272+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "0c54c70e130b"
down_revision: str | None = "0fa42738c500"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounting_periods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("period_no", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("closed_by_id", sa.UUID(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('OPEN', 'CLOSED', 'LOCKED')",
            name=op.f("ck_accounting_periods_status_valid"),
        ),
        sa.CheckConstraint(
            "period_no BETWEEN 1 AND 12", name=op.f("ck_accounting_periods_period_no_valid")
        ),
        sa.CheckConstraint(
            "start_date < end_date", name=op.f("ck_accounting_periods_period_range_valid")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_accounting_periods_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounting_periods")),
        sa.UniqueConstraint("company_id", "fiscal_year", "period_no", name="uq_periods_fy_no"),
    )
    op.create_index(
        op.f("ix_accounting_periods_company_id"), "accounting_periods", ["company_id"], unique=False
    )
    op.create_index(
        "ix_periods_range",
        "accounting_periods",
        ["company_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("normal_balance", sa.String(length=2), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("path", sa.String(length=2000), nullable=False),
        sa.Column("is_postable", sa.Boolean(), nullable=False),
        sa.Column("requires_project", sa.Boolean(), nullable=False),
        sa.Column("requires_cost_center", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "account_type IN ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', 'COGS_DEV_COST')",
            name=op.f("ck_accounts_account_type_valid"),
        ),
        sa.CheckConstraint(
            "normal_balance IN ('DR', 'CR')", name=op.f("ck_accounts_normal_balance_valid")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_accounts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["accounts.id"],
            name=op.f("fk_accounts_parent_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("company_id", "code", name="uq_accounts_code"),
    )
    op.create_index(op.f("ix_accounts_company_id"), "accounts", ["company_id"], unique=False)
    op.create_index(op.f("ix_accounts_deleted_at"), "accounts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_accounts_parent_id"), "accounts", ["parent_id"], unique=False)
    op.create_index("ix_accounts_path", "accounts", ["path"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("je_number", sa.String(length=40), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_debit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_request_id", sa.UUID(), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by_id", sa.UUID(), nullable=True),
        sa.Column("reversal_of_id", sa.UUID(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('MANUAL', 'GRN', 'INVENTORY', 'INVOICE', 'PAYMENT', 'PAYROLL', 'DEPRECIATION', 'OPENING_BALANCE')",
            name=op.f("ck_journal_entries_source_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_APPROVAL', 'POSTED', 'REVERSED')",
            name=op.f("ck_journal_entries_status_valid"),
        ),
        sa.CheckConstraint(
            "total_credit >= 0", name=op.f("ck_journal_entries_total_credit_non_negative")
        ),
        sa.CheckConstraint(
            "total_debit >= 0", name=op.f("ck_journal_entries_total_debit_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_journal_entries_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["accounting_periods.id"],
            name=op.f("fk_journal_entries_period_id_accounting_periods"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["journal_entries.id"],
            name=op.f("fk_journal_entries_reversal_of_id_journal_entries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
        sa.UniqueConstraint("company_id", "je_number", name="uq_journal_entries_number"),
    )
    op.create_index(
        op.f("ix_journal_entries_company_id"), "journal_entries", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_period_id"), "journal_entries", ["period_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_reversal_of_id"),
        "journal_entries",
        ["reversal_of_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entries_source_id"), "journal_entries", ["source_id"], unique=False
    )
    op.create_index(
        "uq_journal_entries_one_reversal",
        "journal_entries",
        ["reversal_of_id"],
        unique=True,
        postgresql_where="reversal_of_id IS NOT NULL",
    )
    op.create_table(
        "journal_entry_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("je_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("debit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("phase_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("cost_center_id", sa.UUID(), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("employee_id", sa.UUID(), nullable=True),
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)",
            name=op.f("ck_journal_entry_lines_moves_one_way"),
        ),
        sa.CheckConstraint("credit >= 0", name=op.f("ck_journal_entry_lines_credit_non_negative")),
        sa.CheckConstraint("debit >= 0", name=op.f("ck_journal_entry_lines_debit_non_negative")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_journal_entry_lines_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cost_center_id"],
            ["cost_centers.id"],
            name=op.f("fk_journal_entry_lines_cost_center_id_cost_centers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_journal_entry_lines_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["je_id"],
            ["journal_entries.id"],
            name=op.f("fk_journal_entry_lines_je_id_journal_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_journal_entry_lines_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["project_phases.id"],
            name=op.f("fk_journal_entry_lines_phase_id_project_phases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_journal_entry_lines_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_journal_entry_lines_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_journal_entry_lines_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entry_lines")),
        sa.UniqueConstraint("je_id", "line_no", name="uq_journal_entry_lines_line"),
    )
    op.create_index(
        op.f("ix_journal_entry_lines_account_id"),
        "journal_entry_lines",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entry_lines_je_id"), "journal_entry_lines", ["je_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_lines_project_id"),
        "journal_entry_lines",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entry_lines_vendor_id"), "journal_entry_lines", ["vendor_id"], unique=False
    )
    # ### end Alembic commands ###

    # A deferred constraint trigger: whatever a transaction does to an entry's
    # lines, its debits equal its credits by the time that transaction commits
    # (docs/02 §12 invariant 1). "Deferred" is what makes this possible without
    # forcing every line to be inserted in a single statement — the check runs
    # once, at commit, against whatever the transaction leaves behind.
    op.execute(
        """
        CREATE FUNCTION krb_check_journal_balance() RETURNS trigger AS $$
        DECLARE
            v_je_id uuid;
            v_debit numeric;
            v_credit numeric;
        BEGIN
            v_je_id := COALESCE(NEW.je_id, OLD.je_id);
            SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0)
              INTO v_debit, v_credit
              FROM journal_entry_lines WHERE je_id = v_je_id;
            IF v_debit <> v_credit THEN
                RAISE EXCEPTION
                    'Journal entry % is not balanced: debits % <> credits %',
                    v_je_id, v_debit, v_credit;
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER journal_entry_lines_balanced
        AFTER INSERT OR UPDATE OR DELETE ON journal_entry_lines
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION krb_check_journal_balance();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS journal_entry_lines_balanced ON journal_entry_lines")
    op.execute("DROP FUNCTION IF EXISTS krb_check_journal_balance()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_entry_lines_vendor_id"), table_name="journal_entry_lines")
    op.drop_index(op.f("ix_journal_entry_lines_project_id"), table_name="journal_entry_lines")
    op.drop_index(op.f("ix_journal_entry_lines_je_id"), table_name="journal_entry_lines")
    op.drop_index(op.f("ix_journal_entry_lines_account_id"), table_name="journal_entry_lines")
    op.drop_table("journal_entry_lines")
    op.drop_index(
        "uq_journal_entries_one_reversal",
        table_name="journal_entries",
        postgresql_where="reversal_of_id IS NOT NULL",
    )
    op.drop_index(op.f("ix_journal_entries_source_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_reversal_of_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_period_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_company_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index("ix_accounts_path", table_name="accounts")
    op.drop_index(op.f("ix_accounts_parent_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_deleted_at"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_company_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index("ix_periods_range", table_name="accounting_periods")
    op.drop_index(op.f("ix_accounting_periods_company_id"), table_name="accounting_periods")
    op.drop_table("accounting_periods")
    # ### end Alembic commands ###
