"""rfqs quotations and purchase orders

Revision ID: 06cad11c4e5d
Revises: a1e7e9334421
Created: 2026-09-25 17:26:22.705871+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "06cad11c4e5d"
down_revision: str | None = "a1e7e9334421"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rfqs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("rfq_number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("purchase_request_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("terms", sa.String(length=4000), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ISSUED', 'CLOSED', 'CANCELLED')",
            name=op.f("ck_rfqs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_rfqs_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_rfqs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"],
            ["purchase_requests.id"],
            name=op.f("fk_rfqs_purchase_request_id_purchase_requests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_rfqs_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfqs")),
        sa.UniqueConstraint("company_id", "rfq_number", name="uq_rfqs_number"),
    )
    op.create_index(op.f("ix_rfqs_company_id"), "rfqs", ["company_id"], unique=False)
    op.create_index(op.f("ix_rfqs_project_id"), "rfqs", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_rfqs_purchase_request_id"), "rfqs", ["purchase_request_id"], unique=False
    )
    op.create_index(op.f("ix_rfqs_site_id"), "rfqs", ["site_id"], unique=False)
    op.create_index("ix_rfqs_status", "rfqs", ["company_id", "status"], unique=False)
    op.create_table(
        "rfq_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rfq_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("pr_item_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_rfq_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_rfq_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pr_item_id"],
            ["purchase_request_items.id"],
            name=op.f("fk_rfq_items_pr_item_id_purchase_request_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"], ["rfqs.id"], name=op.f("fk_rfq_items_rfq_id_rfqs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_rfq_items_unit_id_units"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfq_items")),
        sa.UniqueConstraint("rfq_id", "line_no", name="uq_rfq_items_line"),
    )
    op.create_index(op.f("ix_rfq_items_material_id"), "rfq_items", ["material_id"], unique=False)
    op.create_index(op.f("ix_rfq_items_rfq_id"), "rfq_items", ["rfq_id"], unique=False)
    op.create_table(
        "rfq_vendors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rfq_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column(
            "invited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("access_token_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('INVITED', 'QUOTED', 'DECLINED', 'NO_RESPONSE')",
            name=op.f("ck_rfq_vendors_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"], ["rfqs.id"], name=op.f("fk_rfq_vendors_rfq_id_rfqs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_rfq_vendors_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfq_vendors")),
        sa.UniqueConstraint("rfq_id", "vendor_id", name="uq_rfq_vendors_vendor"),
    )
    op.create_index(op.f("ix_rfq_vendors_rfq_id"), "rfq_vendors", ["rfq_id"], unique=False)
    op.create_index(op.f("ix_rfq_vendors_vendor_id"), "rfq_vendors", ["vendor_id"], unique=False)
    op.create_table(
        "vendor_quotations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("quotation_number", sa.String(length=40), nullable=False),
        sa.Column("rfq_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("vendor_reference", sa.String(length=80), nullable=True),
        sa.Column("quote_date", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("delivery_days", sa.Integer(), nullable=True),
        sa.Column("payment_terms", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("selection_reason", sa.String(length=2000), nullable=True),
        sa.Column("selected_by_id", sa.UUID(), nullable=True),
        sa.Column("selected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status <> 'SELECTED' OR (selection_reason IS NOT NULL AND selected_by_id IS NOT NULL)",
            name=op.f("ck_vendor_quotations_selected_needs_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('RECEIVED', 'SHORTLISTED', 'SELECTED', 'REJECTED')",
            name=op.f("ck_vendor_quotations_status_valid"),
        ),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_vendor_quotations_total_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendor_quotations_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_vendor_quotations_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"],
            ["rfqs.id"],
            name=op.f("fk_vendor_quotations_rfq_id_rfqs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_vendor_quotations_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_quotations_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_quotations")),
        sa.UniqueConstraint("company_id", "quotation_number", name="uq_vendor_quotations_number"),
        sa.UniqueConstraint("rfq_id", "vendor_id", name="uq_vendor_quotations_rfq_vendor"),
    )
    op.create_index(
        op.f("ix_vendor_quotations_company_id"), "vendor_quotations", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_quotations_project_id"), "vendor_quotations", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_quotations_rfq_id"), "vendor_quotations", ["rfq_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_quotations_site_id"), "vendor_quotations", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_quotations_vendor_id"), "vendor_quotations", ["vendor_id"], unique=False
    )
    op.create_index(
        "uq_vendor_quotations_one_selected",
        "vendor_quotations",
        ["rfq_id"],
        unique=True,
        postgresql_where=sa.text("status = 'SELECTED'"),
    )
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("po_number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("amendment_reason", sa.String(length=1000), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("phase_id", sa.UUID(), nullable=True),
        sa.Column("cost_center_id", sa.UUID(), nullable=True),
        sa.Column("quotation_id", sa.UUID(), nullable=True),
        sa.Column("po_date", sa.Date(), nullable=False),
        sa.Column("expected_delivery_date", sa.Date(), nullable=True),
        sa.Column("delivery_address", sa.String(length=500), nullable=True),
        sa.Column("payment_terms", sa.String(length=200), nullable=True),
        sa.Column("terms_and_conditions", sa.String(length=4000), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column("approval_request_id", sa.UUID(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.String(length=500), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'SENT', 'ACKNOWLEDGED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CLOSED', 'CANCELLED')",
            name=op.f("ck_purchase_orders_status_valid"),
        ),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_purchase_orders_total_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_purchase_orders_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cost_center_id"],
            ["cost_centers.id"],
            name=op.f("fk_purchase_orders_cost_center_id_cost_centers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["project_phases.id"],
            name=op.f("fk_purchase_orders_phase_id_project_phases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_purchase_orders_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["vendor_quotations.id"],
            name=op.f("fk_purchase_orders_quotation_id_vendor_quotations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_purchase_orders_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_purchase_orders_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint("company_id", "po_number", name="uq_purchase_orders_number"),
    )
    op.create_index(
        op.f("ix_purchase_orders_company_id"), "purchase_orders", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_project_id"), "purchase_orders", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_quotation_id"), "purchase_orders", ["quotation_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_site_id"), "purchase_orders", ["site_id"], unique=False
    )
    op.create_index(
        "ix_purchase_orders_status", "purchase_orders", ["company_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_vendor_id"), "purchase_orders", ["vendor_id"], unique=False
    )
    op.create_table(
        "vendor_quotation_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quotation_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("rfq_item_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("tax_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("delivery_days", sa.Integer(), nullable=True),
        sa.Column("remarks", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "discount_pct BETWEEN 0 AND 100",
            name=op.f("ck_vendor_quotation_items_discount_pct_range"),
        ),
        sa.CheckConstraint(
            "line_total >= 0", name=op.f("ck_vendor_quotation_items_line_total_non_negative")
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_vendor_quotation_items_quantity_positive")
        ),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_vendor_quotation_items_rate_non_negative")),
        sa.CheckConstraint(
            "tax_pct BETWEEN 0 AND 100", name=op.f("ck_vendor_quotation_items_tax_pct_range")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_vendor_quotation_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["vendor_quotations.id"],
            name=op.f("fk_vendor_quotation_items_quotation_id_vendor_quotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rfq_item_id"],
            ["rfq_items.id"],
            name=op.f("fk_vendor_quotation_items_rfq_item_id_rfq_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_vendor_quotation_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_quotation_items")),
        sa.UniqueConstraint("quotation_id", "line_no", name="uq_vendor_quotation_items_line"),
        sa.UniqueConstraint(
            "quotation_id", "rfq_item_id", name="uq_vendor_quotation_items_rfq_item"
        ),
    )
    op.create_index(
        op.f("ix_vendor_quotation_items_quotation_id"),
        "vendor_quotation_items",
        ["quotation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_quotation_items_rfq_item_id"),
        "vendor_quotation_items",
        ["rfq_item_id"],
        unique=False,
    )
    op.create_table(
        "purchase_order_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("po_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("tax_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("received_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("accepted_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("invoiced_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("pr_item_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "accepted_quantity >= 0",
            name=op.f("ck_purchase_order_items_accepted_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "discount_pct BETWEEN 0 AND 100",
            name=op.f("ck_purchase_order_items_discount_pct_range"),
        ),
        sa.CheckConstraint(
            "invoiced_quantity >= 0",
            name=op.f("ck_purchase_order_items_invoiced_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "line_total >= 0", name=op.f("ck_purchase_order_items_line_total_non_negative")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_order_items_quantity_positive")),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_purchase_order_items_rate_non_negative")),
        sa.CheckConstraint(
            "received_quantity >= 0",
            name=op.f("ck_purchase_order_items_received_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "tax_pct BETWEEN 0 AND 100", name=op.f("ck_purchase_order_items_tax_pct_range")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_purchase_order_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_order_items_po_id_purchase_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pr_item_id"],
            ["purchase_request_items.id"],
            name=op.f("fk_purchase_order_items_pr_item_id_purchase_request_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_purchase_order_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_items")),
        sa.UniqueConstraint("po_id", "line_no", name="uq_purchase_order_items_line"),
    )
    op.create_index(
        op.f("ix_purchase_order_items_material_id"),
        "purchase_order_items",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_items_po_id"), "purchase_order_items", ["po_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_items_pr_item_id"),
        "purchase_order_items",
        ["pr_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_order_items_pr_item_id"), table_name="purchase_order_items")
    op.drop_index(op.f("ix_purchase_order_items_po_id"), table_name="purchase_order_items")
    op.drop_index(op.f("ix_purchase_order_items_material_id"), table_name="purchase_order_items")
    op.drop_table("purchase_order_items")
    op.drop_index(
        op.f("ix_vendor_quotation_items_rfq_item_id"), table_name="vendor_quotation_items"
    )
    op.drop_index(
        op.f("ix_vendor_quotation_items_quotation_id"), table_name="vendor_quotation_items"
    )
    op.drop_table("vendor_quotation_items")
    op.drop_index(op.f("ix_purchase_orders_vendor_id"), table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_status", table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_site_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_quotation_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_project_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_company_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(
        "uq_vendor_quotations_one_selected",
        table_name="vendor_quotations",
        postgresql_where=sa.text("status = 'SELECTED'"),
    )
    op.drop_index(op.f("ix_vendor_quotations_vendor_id"), table_name="vendor_quotations")
    op.drop_index(op.f("ix_vendor_quotations_site_id"), table_name="vendor_quotations")
    op.drop_index(op.f("ix_vendor_quotations_rfq_id"), table_name="vendor_quotations")
    op.drop_index(op.f("ix_vendor_quotations_project_id"), table_name="vendor_quotations")
    op.drop_index(op.f("ix_vendor_quotations_company_id"), table_name="vendor_quotations")
    op.drop_table("vendor_quotations")
    op.drop_index(op.f("ix_rfq_vendors_vendor_id"), table_name="rfq_vendors")
    op.drop_index(op.f("ix_rfq_vendors_rfq_id"), table_name="rfq_vendors")
    op.drop_table("rfq_vendors")
    op.drop_index(op.f("ix_rfq_items_rfq_id"), table_name="rfq_items")
    op.drop_index(op.f("ix_rfq_items_material_id"), table_name="rfq_items")
    op.drop_table("rfq_items")
    op.drop_index("ix_rfqs_status", table_name="rfqs")
    op.drop_index(op.f("ix_rfqs_site_id"), table_name="rfqs")
    op.drop_index(op.f("ix_rfqs_purchase_request_id"), table_name="rfqs")
    op.drop_index(op.f("ix_rfqs_project_id"), table_name="rfqs")
    op.drop_index(op.f("ix_rfqs_company_id"), table_name="rfqs")
    op.drop_table("rfqs")
    # ### end Alembic commands ###
