"""vendor invoices, tax codes, 3-way match

Revision ID: 9754202c43d9
Revises: aa2278042938
Created: 2026-09-28 14:49:00.364527+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "9754202c43d9"
down_revision: str | None = "aa2278042938"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("tax_type", sa.String(length=20), nullable=False),
        sa.Column("rate_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("section_code", sa.String(length=20), nullable=True),
        sa.Column("applies_to", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "applies_to IN ('GOODS', 'SERVICES', 'PAYMENT')",
            name=op.f("ck_tax_codes_applies_to_valid"),
        ),
        sa.CheckConstraint(
            "tax_type IN ('SALES_TAX', 'WITHHOLDING')", name=op.f("ck_tax_codes_tax_type_valid")
        ),
        sa.CheckConstraint("rate_pct BETWEEN 0 AND 100", name=op.f("ck_tax_codes_rate_pct_range")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_tax_codes_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_codes")),
        sa.UniqueConstraint("company_id", "code", name="uq_tax_codes_code"),
    )
    op.create_index(op.f("ix_tax_codes_company_id"), "tax_codes", ["company_id"], unique=False)
    op.create_table(
        "vendor_invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("invoice_number", sa.String(length=40), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("vendor_invoice_ref", sa.String(length=60), nullable=False),
        sa.Column("purchase_order_id", sa.UUID(), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("withholding_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_MATCH', 'MATCHED', 'DISPUTED', 'APPROVED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')",
            name=op.f("ck_vendor_invoices_status_valid"),
        ),
        sa.CheckConstraint(
            "paid_amount >= 0", name=op.f("ck_vendor_invoices_paid_amount_non_negative")
        ),
        sa.CheckConstraint("subtotal >= 0", name=op.f("ck_vendor_invoices_subtotal_non_negative")),
        sa.CheckConstraint(
            "tax_amount >= 0", name=op.f("ck_vendor_invoices_tax_amount_non_negative")
        ),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_vendor_invoices_total_amount_non_negative")
        ),
        sa.CheckConstraint(
            "withholding_amount >= 0",
            name=op.f("ck_vendor_invoices_withholding_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendor_invoices_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_vendor_invoices_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_invoices_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_invoices")),
        sa.UniqueConstraint("company_id", "invoice_number", name="uq_vendor_invoices_number"),
        sa.UniqueConstraint(
            "company_id", "vendor_id", "vendor_invoice_ref", name="uq_vendor_invoices_ref"
        ),
    )
    op.create_index(
        op.f("ix_vendor_invoices_company_id"), "vendor_invoices", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_invoices_purchase_order_id"),
        "vendor_invoices",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_invoices_vendor_id"), "vendor_invoices", ["vendor_id"], unique=False
    )
    op.create_table(
        "vendor_invoice_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("po_item_id", sa.UUID(), nullable=True),
        sa.Column("grn_item_id", sa.UUID(), nullable=True),
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=True),
        sa.Column("rate", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_code_id", sa.UUID(), nullable=True),
        sa.Column("tax_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_vendor_invoice_items_amount_non_negative")),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_vendor_invoice_items_quantity_non_negative")
        ),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_vendor_invoice_items_rate_non_negative")),
        sa.CheckConstraint(
            "tax_amount >= 0", name=op.f("ck_vendor_invoice_items_tax_amount_non_negative")
        ),
        sa.CheckConstraint(
            "tax_pct BETWEEN 0 AND 100", name=op.f("ck_vendor_invoice_items_tax_pct_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_vendor_invoice_items_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grn_item_id"],
            ["grn_items.id"],
            name=op.f("fk_vendor_invoice_items_grn_item_id_grn_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["vendor_invoices.id"],
            name=op.f("fk_vendor_invoice_items_invoice_id_vendor_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_vendor_invoice_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["po_item_id"],
            ["purchase_order_items.id"],
            name=op.f("fk_vendor_invoice_items_po_item_id_purchase_order_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tax_code_id"],
            ["tax_codes.id"],
            name=op.f("fk_vendor_invoice_items_tax_code_id_tax_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_vendor_invoice_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_invoice_items")),
        sa.UniqueConstraint("invoice_id", "line_no", name="uq_vendor_invoice_items_line"),
    )
    op.create_index(
        op.f("ix_vendor_invoice_items_invoice_id"),
        "vendor_invoice_items",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "vendor_invoice_matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_item_id", sa.UUID(), nullable=False),
        sa.Column("po_item_id", sa.UUID(), nullable=True),
        sa.Column("grn_item_id", sa.UUID(), nullable=True),
        sa.Column("match_type", sa.String(length=10), nullable=False),
        sa.Column("qty_variance", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("rate_variance", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("amount_variance", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("within_tolerance", sa.Boolean(), nullable=False),
        sa.Column("tolerance_rule_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "match_type IN ('THREE_WAY', 'TWO_WAY', 'UNMATCHED')",
            name=op.f("ck_vendor_invoice_matches_match_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["grn_item_id"],
            ["grn_items.id"],
            name=op.f("fk_vendor_invoice_matches_grn_item_id_grn_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_item_id"],
            ["vendor_invoice_items.id"],
            name=op.f("fk_vendor_invoice_matches_invoice_item_id_vendor_invoice_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["po_item_id"],
            ["purchase_order_items.id"],
            name=op.f("fk_vendor_invoice_matches_po_item_id_purchase_order_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_invoice_matches")),
        sa.UniqueConstraint(
            "invoice_item_id", name=op.f("uq_vendor_invoice_matches_invoice_item_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vendor_invoice_matches")
    op.drop_index(op.f("ix_vendor_invoice_items_invoice_id"), table_name="vendor_invoice_items")
    op.drop_table("vendor_invoice_items")
    op.drop_index(op.f("ix_vendor_invoices_vendor_id"), table_name="vendor_invoices")
    op.drop_index(op.f("ix_vendor_invoices_purchase_order_id"), table_name="vendor_invoices")
    op.drop_index(op.f("ix_vendor_invoices_company_id"), table_name="vendor_invoices")
    op.drop_table("vendor_invoices")
    op.drop_index(op.f("ix_tax_codes_company_id"), table_name="tax_codes")
    op.drop_table("tax_codes")
    # ### end Alembic commands ###
