"""counter purchases

Revision ID: 997ba5bd48fd
Revises: be8d4f4cbd69
Created: 2026-09-26 19:00:10.320516+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "997ba5bd48fd"
down_revision: str | None = "be8d4f4cbd69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grns", sa.Column("counter_reference", sa.String(length=60), nullable=True))
    # ### end Alembic commands ###
    # Stock arrives on a recorded delivery or against a named bill; never on neither.
    op.create_check_constraint(
        op.f("ck_grns_counter_purchase_needs_reference"),
        "grns",
        "delivery_id IS NOT NULL OR counter_reference IS NOT NULL",
    )
    # A bill is entered once per vendor.
    op.create_index(
        "uq_grns_live_counter_reference",
        "grns",
        ["company_id", "vendor_id", "counter_reference"],
        unique=True,
        postgresql_where=sa.text("status <> 'CANCELLED' AND counter_reference IS NOT NULL"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_grns_live_counter_reference",
        table_name="grns",
        postgresql_where=sa.text("status <> 'CANCELLED' AND counter_reference IS NOT NULL"),
    )
    op.drop_constraint(op.f("ck_grns_counter_purchase_needs_reference"), "grns", type_="check")
    op.drop_column("grns", "counter_reference")
    # ### end Alembic commands ###
