"""mobile sync cursor

Revision ID: 084cfc193976
Revises: af8136a03a41
Created: 2026-09-26 05:54:33.271560+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "084cfc193976"
down_revision: str | None = "af8136a03a41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES = (
    "materials",
    "units",
    "truck_types",
    "vendors",
    "sites",
    "business_rules",
    "purchase_orders",
)


def upgrade() -> None:
    op.execute("CREATE SEQUENCE global_change_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("business_rules", sa.Column("server_seq", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_business_rules_server_seq"), "business_rules", ["server_seq"], unique=False
    )
    op.add_column("materials", sa.Column("server_seq", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_materials_server_seq"), "materials", ["server_seq"], unique=False)
    op.add_column("purchase_orders", sa.Column("server_seq", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_purchase_orders_server_seq"), "purchase_orders", ["server_seq"], unique=False
    )
    op.add_column("sites", sa.Column("server_seq", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_sites_server_seq"), "sites", ["server_seq"], unique=False)
    op.add_column("truck_types", sa.Column("server_seq", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_truck_types_server_seq"), "truck_types", ["server_seq"], unique=False)
    op.add_column("units", sa.Column("server_seq", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_units_server_seq"), "units", ["server_seq"], unique=False)
    op.add_column("vendors", sa.Column("server_seq", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_vendors_server_seq"), "vendors", ["server_seq"], unique=False)
    # ### end Alembic commands ###

    # Rows that already exist get a place in the sequence, oldest first, so a
    # phone's first pull sees all of them.
    for table in TABLES:
        op.execute(f"UPDATE {table} SET server_seq = nextval('global_change_seq')")  # noqa: S608 - constant table names

    # The trigger, not the application, assigns the cursor: it is the only thing
    # that also fires on UPDATE, and it cannot be forgotten by a new code path.
    op.execute(
        """
        CREATE FUNCTION krb_bump_server_seq() RETURNS trigger AS $$
        BEGIN
            NEW.server_seq := nextval('global_change_seq');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in TABLES:
        op.execute(
            f"""
            CREATE TRIGGER {table}_server_seq
            BEFORE INSERT OR UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION krb_bump_server_seq();
            """
        )

    # A change to a child row is a change to what the phone caches for its parent:
    # a material's alternate units, a purchase order's lines and what was received.
    op.execute(
        """
        CREATE FUNCTION krb_bump_material_seq() RETURNS trigger AS $$
        BEGIN
            UPDATE materials SET server_seq = nextval('global_change_seq')
            WHERE id = NEW.material_id;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER material_units_bump_material
        AFTER INSERT OR UPDATE ON material_units
        FOR EACH ROW EXECUTE FUNCTION krb_bump_material_seq();
        """
    )
    op.execute(
        """
        CREATE FUNCTION krb_bump_purchase_order_seq() RETURNS trigger AS $$
        BEGIN
            UPDATE purchase_orders SET server_seq = nextval('global_change_seq')
            WHERE id = NEW.po_id;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER purchase_order_items_bump_order
        AFTER INSERT OR UPDATE ON purchase_order_items
        FOR EACH ROW EXECUTE FUNCTION krb_bump_purchase_order_seq();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS purchase_order_items_bump_order ON purchase_order_items")
    op.execute("DROP FUNCTION IF EXISTS krb_bump_purchase_order_seq()")
    op.execute("DROP TRIGGER IF EXISTS material_units_bump_material ON material_units")
    op.execute("DROP FUNCTION IF EXISTS krb_bump_material_seq()")
    for table in TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_server_seq ON {table}")
    op.execute("DROP FUNCTION IF EXISTS krb_bump_server_seq()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendors_server_seq"), table_name="vendors")
    op.drop_column("vendors", "server_seq")
    op.drop_index(op.f("ix_units_server_seq"), table_name="units")
    op.drop_column("units", "server_seq")
    op.drop_index(op.f("ix_truck_types_server_seq"), table_name="truck_types")
    op.drop_column("truck_types", "server_seq")
    op.drop_index(op.f("ix_sites_server_seq"), table_name="sites")
    op.drop_column("sites", "server_seq")
    op.drop_index(op.f("ix_purchase_orders_server_seq"), table_name="purchase_orders")
    op.drop_column("purchase_orders", "server_seq")
    op.drop_index(op.f("ix_materials_server_seq"), table_name="materials")
    op.drop_column("materials", "server_seq")
    op.drop_index(op.f("ix_business_rules_server_seq"), table_name="business_rules")
    op.drop_column("business_rules", "server_seq")
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS global_change_seq")
