"""bank accounts, payment requests, payments

Revision ID: 67bd68239087
Revises: 9754202c43d9
Created: 2026-09-29 12:24:43.556256+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "67bd68239087"
down_revision: str | None = "9754202c43d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("account_title", sa.String(length=160), nullable=False),
        sa.Column("account_no", sa.String(length=40), nullable=False),
        sa.Column("iban", sa.String(length=40), nullable=True),
        sa.Column("bank_name", sa.String(length=160), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("gl_account_id", sa.UUID(), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_bank_accounts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["gl_account_id"],
            ["accounts.id"],
            name=op.f("fk_bank_accounts_gl_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_accounts")),
        sa.UniqueConstraint("company_id", "account_no", name="uq_bank_accounts_account_no"),
    )
    op.create_index(
        op.f("ix_bank_accounts_company_id"), "bank_accounts", ["company_id"], unique=False
    )
    op.create_table(
        "payment_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("request_number", sa.String(length=40), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("is_advance", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column("approval_request_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "priority IN ('NORMAL', 'URGENT')", name=op.f("ck_payment_requests_priority_valid")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'PAID', 'CANCELLED')",
            name=op.f("ck_payment_requests_status_valid"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_payment_requests_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payment_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_payment_requests_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_requests")),
        sa.UniqueConstraint("company_id", "request_number", name="uq_payment_requests_number"),
    )
    op.create_index(
        op.f("ix_payment_requests_company_id"), "payment_requests", ["company_id"], unique=False
    )
    op.create_index(
        "ix_payment_requests_status", "payment_requests", ["company_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_payment_requests_vendor_id"), "payment_requests", ["vendor_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("payment_number", sa.String(length=40), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("payment_request_id", sa.UUID(), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("direction", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("bank_account_id", sa.UUID(), nullable=True),
        sa.Column("instrument_no", sa.String(length=60), nullable=True),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("withholding_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("direction IN ('OUT', 'IN')", name=op.f("ck_payments_direction_valid")),
        sa.CheckConstraint(
            "method IN ('BANK_TRANSFER', 'CHEQUE', 'CASH', 'ONLINE')",
            name=op.f("ck_payments_method_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('ISSUED', 'CLEARED', 'CANCELLED')", name=op.f("ck_payments_status_valid")
        ),
        sa.CheckConstraint(
            "allocated_amount >= 0", name=op.f("ck_payments_allocated_amount_non_negative")
        ),
        sa.CheckConstraint("gross_amount >= 0", name=op.f("ck_payments_gross_amount_non_negative")),
        sa.CheckConstraint("net_amount >= 0", name=op.f("ck_payments_net_amount_non_negative")),
        sa.CheckConstraint(
            "withholding_amount >= 0", name=op.f("ck_payments_withholding_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_payments_bank_account_id_bank_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_request_id"],
            ["payment_requests.id"],
            name=op.f("fk_payments_payment_request_id_payment_requests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_payments_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("company_id", "payment_number", name="uq_payments_number"),
    )
    op.create_index(op.f("ix_payments_company_id"), "payments", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_payments_payment_request_id"), "payments", ["payment_request_id"], unique=False
    )
    op.create_index("ix_payments_status", "payments", ["company_id", "status"], unique=False)
    op.create_index(op.f("ix_payments_vendor_id"), "payments", ["vendor_id"], unique=False)
    op.create_table(
        "payment_allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "allocated_amount >= 0",
            name=op.f("ck_payment_allocations_allocated_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["vendor_invoices.id"],
            name=op.f("fk_payment_allocations_invoice_id_vendor_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_allocations_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_allocations")),
        sa.UniqueConstraint("payment_id", "invoice_id", name="uq_payment_allocations_pair"),
    )
    op.create_index(
        op.f("ix_payment_allocations_invoice_id"),
        "payment_allocations",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_allocations_payment_id"),
        "payment_allocations",
        ["payment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_allocations_payment_id"), table_name="payment_allocations")
    op.drop_index(op.f("ix_payment_allocations_invoice_id"), table_name="payment_allocations")
    op.drop_table("payment_allocations")
    op.drop_index(op.f("ix_payments_vendor_id"), table_name="payments")
    op.drop_index("ix_payments_status", table_name="payments")
    op.drop_index(op.f("ix_payments_payment_request_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_company_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_payment_requests_vendor_id"), table_name="payment_requests")
    op.drop_index("ix_payment_requests_status", table_name="payment_requests")
    op.drop_index(op.f("ix_payment_requests_company_id"), table_name="payment_requests")
    op.drop_table("payment_requests")
    op.drop_index(op.f("ix_bank_accounts_company_id"), table_name="bank_accounts")
    op.drop_table("bank_accounts")
    # ### end Alembic commands ###
