"""stock issues transfers adjustments

Revision ID: be8d4f4cbd69
Revises: 084cfc193976
Created: 2026-09-26 17:46:39.585480+00:00

Checklist before committing this migration:
  - Review every generated statement by hand; autogenerate is a draft.
  - No table rewrite on a hot table (deliveries, inventory_transactions,
    journal_entry_lines, audit_logs).
  - New indexes on large tables use CREATE INDEX CONCURRENTLY, which requires
    running outside a transaction (see the op.get_context() note below).
  - Column changes follow expand -> deploy -> contract across two releases.
  - downgrade() is implemented, or a comment explains why it cannot be.
"""

from __future__ import annotations

from collections.abc import Sequence

# Imported unconditionally: needed whenever a migration touches a geography column.
import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "be8d4f4cbd69"
down_revision: str | None = "084cfc193976"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_adjustments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("adjustment_number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("reason_code", sa.String(length=20), nullable=False),
        sa.Column("reason_note", sa.String(length=500), nullable=False),
        sa.Column("adjustment_date", sa.Date(), nullable=False),
        sa.Column("approval_request_id", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "reason_code IN ('COUNT_CORRECTION', 'DAMAGE', 'WASTAGE', 'LOSS', 'THEFT', 'EXPIRED', 'OPENING_BALANCE', 'OTHER')",
            name=op.f("ck_stock_adjustments_reason_code_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR cancel_reason IS NOT NULL",
            name=op.f("ck_stock_adjustments_cancel_needs_reason"),
        ),
        sa.CheckConstraint(
            "status <> 'POSTED' OR approval_request_id IS NOT NULL",
            name=op.f("ck_stock_adjustments_posted_needs_approval"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_APPROVAL', 'POSTED', 'REJECTED', 'CANCELLED')",
            name=op.f("ck_stock_adjustments_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_adjustments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_stock_adjustments_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_stock_adjustments_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_adjustments_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustments")),
        sa.UniqueConstraint("company_id", "adjustment_number", name="uq_stock_adjustments_number"),
    )
    op.create_index(
        op.f("ix_stock_adjustments_company_id"), "stock_adjustments", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_adjustments_project_id"), "stock_adjustments", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_adjustments_site_id"), "stock_adjustments", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_adjustments_warehouse_id"),
        "stock_adjustments",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "stock_issues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("issue_number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("issued_to_type", sa.String(length=15), nullable=False),
        sa.Column("issued_to_name", sa.String(length=160), nullable=False),
        sa.Column("purpose", sa.String(length=300), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_by_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "issued_to_type IN ('EMPLOYEE', 'CONTRACTOR', 'WORK_ORDER')",
            name=op.f("ck_stock_issues_issued_to_type_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR cancel_reason IS NOT NULL",
            name=op.f("ck_stock_issues_cancel_needs_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ISSUED', 'CANCELLED')", name=op.f("ck_stock_issues_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_issues_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_stock_issues_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_stock_issues_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_issues_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_issues")),
        sa.UniqueConstraint("company_id", "issue_number", name="uq_stock_issues_number"),
    )
    op.create_index(
        op.f("ix_stock_issues_company_id"), "stock_issues", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_issues_project_id"), "stock_issues", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_stock_issues_site_id"), "stock_issues", ["site_id"], unique=False)
    op.create_index(
        op.f("ix_stock_issues_warehouse_id"), "stock_issues", ["warehouse_id"], unique=False
    )
    op.create_table(
        "stock_transfers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("transfer_number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("from_warehouse_id", sa.UUID(), nullable=False),
        sa.Column("to_warehouse_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("to_project_id", sa.UUID(), nullable=True),
        sa.Column("to_site_id", sa.UUID(), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=False),
        sa.Column("vehicle_number", sa.String(length=30), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_by_id", sa.UUID(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_by_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR cancel_reason IS NOT NULL",
            name=op.f("ck_stock_transfers_cancel_needs_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED')",
            name=op.f("ck_stock_transfers_status_valid"),
        ),
        sa.CheckConstraint(
            "from_warehouse_id <> to_warehouse_id",
            name=op.f("ck_stock_transfers_different_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_transfers_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_transfers_from_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_stock_transfers_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_stock_transfers_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_project_id"],
            ["projects.id"],
            name=op.f("fk_stock_transfers_to_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_site_id"],
            ["sites.id"],
            name=op.f("fk_stock_transfers_to_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_transfers_to_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfers")),
        sa.UniqueConstraint("company_id", "transfer_number", name="uq_stock_transfers_number"),
    )
    op.create_index(
        op.f("ix_stock_transfers_company_id"), "stock_transfers", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_from_warehouse_id"),
        "stock_transfers",
        ["from_warehouse_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_project_id"), "stock_transfers", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_site_id"), "stock_transfers", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_to_site_id"), "stock_transfers", ["to_site_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_to_warehouse_id"),
        "stock_transfers",
        ["to_warehouse_id"],
        unique=False,
    )
    op.create_table(
        "stock_adjustment_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("adjustment_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("value_delta", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("system_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("inventory_txn_id", sa.UUID(), nullable=True),
        sa.Column("remarks", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "quantity_delta <> 0", name=op.f("ck_stock_adjustment_items_delta_not_zero")
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["stock_adjustments.id"],
            name=op.f("fk_stock_adjustment_items_adjustment_id_stock_adjustments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_stock_adjustment_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustment_items")),
        sa.UniqueConstraint("adjustment_id", "line_no", name="uq_stock_adjustment_items_line"),
    )
    op.create_index(
        op.f("ix_stock_adjustment_items_adjustment_id"),
        "stock_adjustment_items",
        ["adjustment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_adjustment_items_material_id"),
        "stock_adjustment_items",
        ["material_id"],
        unique=False,
    )
    op.create_table(
        "stock_issue_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("inventory_txn_id", sa.UUID(), nullable=True),
        sa.Column("remarks", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_issue_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["stock_issues.id"],
            name=op.f("fk_stock_issue_items_issue_id_stock_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_stock_issue_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_stock_issue_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_issue_items")),
        sa.UniqueConstraint("issue_id", "line_no", name="uq_stock_issue_items_line"),
    )
    op.create_index(
        op.f("ix_stock_issue_items_issue_id"), "stock_issue_items", ["issue_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_issue_items_material_id"), "stock_issue_items", ["material_id"], unique=False
    )
    op.create_table(
        "stock_transfer_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transfer_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("out_txn_id", sa.UUID(), nullable=True),
        sa.Column("in_txn_id", sa.UUID(), nullable=True),
        sa.Column("remarks", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_transfer_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_stock_transfer_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["stock_transfers.id"],
            name=op.f("fk_stock_transfer_items_transfer_id_stock_transfers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_stock_transfer_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfer_items")),
        sa.UniqueConstraint("transfer_id", "line_no", name="uq_stock_transfer_items_line"),
    )
    op.create_index(
        op.f("ix_stock_transfer_items_material_id"),
        "stock_transfer_items",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfer_items_transfer_id"),
        "stock_transfer_items",
        ["transfer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_transfer_items_transfer_id"), table_name="stock_transfer_items")
    op.drop_index(op.f("ix_stock_transfer_items_material_id"), table_name="stock_transfer_items")
    op.drop_table("stock_transfer_items")
    op.drop_index(op.f("ix_stock_issue_items_material_id"), table_name="stock_issue_items")
    op.drop_index(op.f("ix_stock_issue_items_issue_id"), table_name="stock_issue_items")
    op.drop_table("stock_issue_items")
    op.drop_index(
        op.f("ix_stock_adjustment_items_material_id"), table_name="stock_adjustment_items"
    )
    op.drop_index(
        op.f("ix_stock_adjustment_items_adjustment_id"), table_name="stock_adjustment_items"
    )
    op.drop_table("stock_adjustment_items")
    op.drop_index(op.f("ix_stock_transfers_to_warehouse_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_to_site_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_site_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_project_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_from_warehouse_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_company_id"), table_name="stock_transfers")
    op.drop_table("stock_transfers")
    op.drop_index(op.f("ix_stock_issues_warehouse_id"), table_name="stock_issues")
    op.drop_index(op.f("ix_stock_issues_site_id"), table_name="stock_issues")
    op.drop_index(op.f("ix_stock_issues_project_id"), table_name="stock_issues")
    op.drop_index(op.f("ix_stock_issues_company_id"), table_name="stock_issues")
    op.drop_table("stock_issues")
    op.drop_index(op.f("ix_stock_adjustments_warehouse_id"), table_name="stock_adjustments")
    op.drop_index(op.f("ix_stock_adjustments_site_id"), table_name="stock_adjustments")
    op.drop_index(op.f("ix_stock_adjustments_project_id"), table_name="stock_adjustments")
    op.drop_index(op.f("ix_stock_adjustments_company_id"), table_name="stock_adjustments")
    op.drop_table("stock_adjustments")
    # ### end Alembic commands ###
